import type { HaeloPrompt } from "./types";

export const CONNECT_PROMPTS: HaeloPrompt[] = [
  {
    id: "connect_001",
    planet: "connect",
    category: "conversation",
    prompt: "What’s a question you could ask someone to get beyond small talk?",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_002",
    planet: "connect",
    category: "conversation",
    prompt: "Tell someone about one interesting thing that happened today.",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_003",
    planet: "connect",
    category: "conversation",
    prompt: "How would you introduce yourself without listing school, age, or activities?",
    depth: "personal",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_004",
    planet: "connect",
    category: "conversation",
    prompt: "What’s something you could ask a new person that would actually interest you?",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_005",
    planet: "connect",
    category: "conversation",
    prompt: "Tell someone about something you’ve been enjoying lately and invite them into the conversation.",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_006",
    planet: "connect",
    category: "conversation",
    prompt: "What topic makes it easy for you to keep a conversation going?",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_007",
    planet: "connect",
    category: "conversation",
    prompt: "What do you do when you don’t know what to say next?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_008",
    planet: "connect",
    category: "conversation",
    prompt: "Practice responding to someone who says, \"My weekend was kind of weird.\"",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_009",
    planet: "connect",
    category: "conversation",
    prompt: "Someone tells you they started a new hobby. Ask three natural follow-up questions.",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_010",
    planet: "connect",
    category: "conversation",
    prompt: "How would you join a conversation that has already started?",
    depth: "light",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_011",
    planet: "connect",
    category: "conversation",
    prompt: "How would you start a conversation with someone you’ve seen several times but never spoken to?",
    depth: "light",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_012",
    planet: "connect",
    category: "conversation",
    prompt: "What makes someone easy for you to talk to?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_013",
    planet: "connect",
    category: "conversation",
    prompt: "What makes conversation feel forced?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_014",
    planet: "connect",
    category: "conversation",
    prompt: "What’s a better question than \"How was your day?\"",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_015",
    planet: "connect",
    category: "conversation",
    prompt: "What kind of question makes you feel like someone genuinely wants to know your answer?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_016",
    planet: "connect",
    category: "conversation",
    prompt: "How do you show someone you’re interested in what they’re saying?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_017",
    planet: "connect",
    category: "conversation",
    prompt: "What helps you feel less pressure to say something impressive?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_018",
    planet: "connect",
    category: "conversation",
    prompt: "How would you keep a conversation going after someone gives a very short answer?",
    depth: "light",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_019",
    planet: "connect",
    category: "conversation",
    prompt: "How would you gracefully end a conversation?",
    depth: "light",
    skill: "conversation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_020",
    planet: "connect",
    category: "conversation",
    prompt: "What’s something you wish people knew about having conversations with you?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_021",
    planet: "connect",
    category: "conversation",
    prompt: "What makes silence comfortable instead of awkward?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_022",
    planet: "connect",
    category: "conversation",
    prompt: "What do you think makes someone memorable after a first conversation?",
    depth: "light",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_023",
    planet: "connect",
    category: "conversation",
    prompt: "How would you reconnect with someone you haven’t spoken to in a while?",
    depth: "light",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_024",
    planet: "connect",
    category: "conversation",
    prompt: "What’s one conversational habit you’d like to become more confident with?",
    depth: "personal",
    skill: "conversation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_025",
    planet: "connect",
    category: "conversation",
    prompt: "What would change if you treated conversation as curiosity rather than performance?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_026",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain something you care about to someone who knows almost nothing about it.",
    depth: "light",
    skill: "clarity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_027",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain an idea without assuming the listener already understands your reasoning.",
    depth: "light",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_028",
    planet: "connect",
    category: "being_understood",
    prompt: "Tell someone why something that seems small to them matters to you.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_029",
    planet: "connect",
    category: "being_understood",
    prompt: "Describe what you need from someone when you’re stressed.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_030",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain why you changed your mind about something.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_031",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain a decision you made that another person might not understand.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_032",
    planet: "connect",
    category: "being_understood",
    prompt: "Describe a situation where your intention and someone else’s interpretation could be different.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_033",
    planet: "connect",
    category: "being_understood",
    prompt: "What do you do when someone misunderstands what you meant?",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_034",
    planet: "connect",
    category: "being_understood",
    prompt: "Practice saying, \"That’s not quite what I meant. What I’m trying to say is…\"",
    depth: "light",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_035",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain an emotion without expecting the other person to fix it.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_036",
    planet: "connect",
    category: "being_understood",
    prompt: "Tell someone why a specific action helped you.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_037",
    planet: "connect",
    category: "being_understood",
    prompt: "Tell someone why a specific action bothered you.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_038",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain what kind of support is actually useful to you.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_039",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain that you need time before talking.",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_040",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain that you want to talk instead of avoiding the issue.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_041",
    planet: "connect",
    category: "being_understood",
    prompt: "What’s something about your communication style that people might misread?",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_042",
    planet: "connect",
    category: "being_understood",
    prompt: "How would you clarify a text message that came across differently than intended?",
    depth: "light",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_043",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain a complicated opinion in three clear points.",
    depth: "light",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_044",
    planet: "connect",
    category: "being_understood",
    prompt: "Explain something personal without giving more detail than you want to.",
    depth: "personal",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_045",
    planet: "connect",
    category: "being_understood",
    prompt: "What makes you feel like someone truly understood what you were trying to say?",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_046",
    planet: "connect",
    category: "being_understood",
    prompt: "When do you tend to over-explain?",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_047",
    planet: "connect",
    category: "being_understood",
    prompt: "When do you tend to under-explain?",
    depth: "personal",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_048",
    planet: "connect",
    category: "being_understood",
    prompt: "What helps you say the important part first?",
    depth: "light",
    skill: "clarity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_049",
    planet: "connect",
    category: "being_understood",
    prompt: "What’s something you want someone in your life to understand better about your perspective?",
    depth: "deep",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_050",
    planet: "connect",
    category: "being_understood",
    prompt: "Say it as clearly as you can.",
    depth: "deep",
    skill: "clarity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_051",
    planet: "connect",
    category: "empathy",
    prompt: "A friend says they had a terrible day. What could you say before offering advice?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_052",
    planet: "connect",
    category: "empathy",
    prompt: "Someone tells you something they’re excited about that you don’t personally care about. How do you respond with genuine interest?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_053",
    planet: "connect",
    category: "empathy",
    prompt: "A friend tells you they’re nervous about something. What would you say?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_054",
    planet: "connect",
    category: "empathy",
    prompt: "Someone shares a problem you can’t solve. How can you still be supportive?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_055",
    planet: "connect",
    category: "empathy",
    prompt: "What’s the difference between listening and waiting for your turn to speak?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_056",
    planet: "connect",
    category: "empathy",
    prompt: "What kind of response makes you feel heard?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_057",
    planet: "connect",
    category: "empathy",
    prompt: "How can you show someone you understood without immediately talking about your own experience?",
    depth: "light",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_058",
    planet: "connect",
    category: "empathy",
    prompt: "Respond to: \"I feel like nobody is taking me seriously.\"",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_059",
    planet: "connect",
    category: "empathy",
    prompt: "Respond to: \"I’m really proud of myself.\"",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_060",
    planet: "connect",
    category: "empathy",
    prompt: "Respond to: \"I messed something up and I feel embarrassed.\"",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_061",
    planet: "connect",
    category: "empathy",
    prompt: "How would you ask whether someone wants advice or just wants you to listen?",
    depth: "light",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_062",
    planet: "connect",
    category: "empathy",
    prompt: "What do you say when you genuinely don’t know how to respond?",
    depth: "light",
    skill: "empathy",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_063",
    planet: "connect",
    category: "empathy",
    prompt: "How can curiosity help when someone has a very different experience from yours?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_064",
    planet: "connect",
    category: "empathy",
    prompt: "What’s a good follow-up question when someone tells you something personal?",
    depth: "light",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_065",
    planet: "connect",
    category: "empathy",
    prompt: "When does sharing your own similar experience help?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_066",
    planet: "connect",
    category: "empathy",
    prompt: "When can it accidentally shift the attention away from them?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_067",
    planet: "connect",
    category: "empathy",
    prompt: "How would you respond to someone who says something you think is unfair while still acknowledging their feelings?",
    depth: "personal",
    skill: "empathy",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_068",
    planet: "connect",
    category: "empathy",
    prompt: "What does being emotionally present in a conversation mean to you?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_069",
    planet: "connect",
    category: "empathy",
    prompt: "How do you want people to respond when you share something difficult?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_070",
    planet: "connect",
    category: "empathy",
    prompt: "What can you learn from that about how to respond to others?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_071",
    planet: "connect",
    category: "empathy",
    prompt: "What’s one phrase people say when trying to help that sometimes feels unhelpful?",
    depth: "light",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_072",
    planet: "connect",
    category: "empathy",
    prompt: "What might be a better response?",
    depth: "light",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_073",
    planet: "connect",
    category: "empathy",
    prompt: "How can you disagree with someone’s interpretation while respecting their experience?",
    depth: "personal",
    skill: "empathy",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_074",
    planet: "connect",
    category: "empathy",
    prompt: "What makes someone feel safe to open up to?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_075",
    planet: "connect",
    category: "empathy",
    prompt: "What kind of listener do you want to be?",
    depth: "personal",
    skill: "empathy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_076",
    planet: "connect",
    category: "repair",
    prompt: "A friend says something you said hurt them, but you didn’t mean it that way. Respond.",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_077",
    planet: "connect",
    category: "repair",
    prompt: "You realize you interrupted someone repeatedly. How would you acknowledge it?",
    depth: "light",
    skill: "repair",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_078",
    planet: "connect",
    category: "repair",
    prompt: "You forgot something that mattered to a friend. What would you say?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_079",
    planet: "connect",
    category: "repair",
    prompt: "Someone apologizes but you still feel hurt. How would you respond?",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_080",
    planet: "connect",
    category: "repair",
    prompt: "You and a friend have both misunderstood each other. How would you restart the conversation?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_081",
    planet: "connect",
    category: "repair",
    prompt: "Practice saying, \"I think we’re talking past each other.\"",
    depth: "light",
    skill: "repair",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_082",
    planet: "connect",
    category: "repair",
    prompt: "Someone says, \"Why are you making this a big deal?\" Explain why you want to talk about it.",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_083",
    planet: "connect",
    category: "repair",
    prompt: "How would you bring up a problem before resentment builds?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_084",
    planet: "connect",
    category: "repair",
    prompt: "How would you tell someone that a joke went too far?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_085",
    planet: "connect",
    category: "repair",
    prompt: "How would you admit you were wrong without over-explaining?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_086",
    planet: "connect",
    category: "repair",
    prompt: "What makes an apology feel sincere to you?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_087",
    planet: "connect",
    category: "repair",
    prompt: "Give an apology that does not include the word \"but.\"",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_088",
    planet: "connect",
    category: "repair",
    prompt: "What is the difference between explaining your intentions and using them as an excuse?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_089",
    planet: "connect",
    category: "repair",
    prompt: "How would you tell someone you need a pause in an argument?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_090",
    planet: "connect",
    category: "repair",
    prompt: "How would you return to the conversation later?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_091",
    planet: "connect",
    category: "repair",
    prompt: "What can you say when a conversation is becoming more intense than productive?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_092",
    planet: "connect",
    category: "repair",
    prompt: "How would you tell someone you still care about them even though you’re upset?",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_093",
    planet: "connect",
    category: "repair",
    prompt: "How would you ask someone what they understood from what you said?",
    depth: "light",
    skill: "repair",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_094",
    planet: "connect",
    category: "repair",
    prompt: "How would you respond when someone gives you feedback that is hard to hear?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_095",
    planet: "connect",
    category: "repair",
    prompt: "What’s a conflict you think could have gone differently with clearer communication?",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_096",
    planet: "connect",
    category: "repair",
    prompt: "What might you have said?",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_097",
    planet: "connect",
    category: "repair",
    prompt: "What would you want the other person to have said?",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_098",
    planet: "connect",
    category: "repair",
    prompt: "How do you know when a relationship problem is worth addressing?",
    depth: "personal",
    skill: "repair",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_099",
    planet: "connect",
    category: "repair",
    prompt: "What makes repair possible after a disagreement?",
    depth: "personal",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_100",
    planet: "connect",
    category: "repair",
    prompt: "Finish this sentence: \"I don’t want us to keep misunderstanding each other, so…\"",
    depth: "deep",
    skill: "repair",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_101",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell a friend something specific you appreciate about them.",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_102",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone why you enjoy spending time with them.",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_103",
    planet: "connect",
    category: "appreciation",
    prompt: "Give a compliment that has nothing to do with appearance.",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_104",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone how they helped you without realizing it.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_105",
    planet: "connect",
    category: "appreciation",
    prompt: "What’s something you admire about a person close to you?",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_106",
    planet: "connect",
    category: "appreciation",
    prompt: "What’s a memory with someone that you’re grateful for?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_107",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone why a small thing they do matters.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_108",
    planet: "connect",
    category: "appreciation",
    prompt: "What quality makes you trust someone?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_109",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone you’re proud of them in a way that feels specific.",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_110",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone you missed them without making it a joke.",
    depth: "personal",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_111",
    planet: "connect",
    category: "appreciation",
    prompt: "How would you tell a friend that you want to spend more time together?",
    depth: "personal",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_112",
    planet: "connect",
    category: "appreciation",
    prompt: "What’s something kind someone once said to you that you still remember?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_113",
    planet: "connect",
    category: "appreciation",
    prompt: "Why did it matter?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_114",
    planet: "connect",
    category: "appreciation",
    prompt: "What is something you wish people complimented each other on more often?",
    depth: "light",
    skill: "appreciation",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "connect_115",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone they made you feel included.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_116",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone that their opinion changed how you thought about something.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_117",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone why you respect them even when you disagree.",
    depth: "personal",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_118",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone what makes your friendship with them different from your other friendships.",
    depth: "personal",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "connect_119",
    planet: "connect",
    category: "appreciation",
    prompt: "What’s something you want to get better at expressing appreciation for?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_120",
    planet: "connect",
    category: "appreciation",
    prompt: "What makes positive feelings awkward to say out loud sometimes?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_121",
    planet: "connect",
    category: "appreciation",
    prompt: "What would make them easier to express?",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_122",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone why you’re glad you know them.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "connect_123",
    planet: "connect",
    category: "appreciation",
    prompt: "Tell someone what you hope they never change about themselves.",
    depth: "personal",
    skill: "appreciation",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_124",
    planet: "connect",
    category: "appreciation",
    prompt: "What would you want someone you care about to know even if you assumed they already knew it?",
    depth: "deep",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_125",
    planet: "connect",
    category: "appreciation",
    prompt: "Say it.",
    depth: "deep",
    skill: "appreciation",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_126",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "Around whom do you feel most comfortable speaking without editing yourself?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_127",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What do those people do that makes that possible?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_128",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "In what kinds of conversations do you tend to become quieter?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_129",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What do you wish you could contribute more often in groups?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_130",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What makes you worry that what you say will be taken the wrong way?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_131",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What helps you recover when a conversation feels awkward?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_132",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What does feeling socially confident mean to you?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_133",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What would it look like to participate more without forcing yourself to become extroverted?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_134",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "When do you feel most listened to?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_135",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "How can you ask for more of that?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_136",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What’s something you want to become more comfortable telling people directly?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_137",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What do you wish you could stop guessing about and simply ask?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_138",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What type of relationship do you want to communicate better in?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_139",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What would \"better\" actually sound like?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_140",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What is one conversation you keep rehearsing in your head?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_141",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What is the simplest honest version of what you want to say?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_142",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "How do you want people to feel after talking with you?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_143",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "How do you want to feel after talking with them?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_144",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What relationship makes you feel like your voice matters?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_145",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "Why?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "connect_146",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What relationship makes it harder to use your voice?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_147",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What communication skill would make that situation easier?",
    depth: "personal",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_148",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What part of yourself do you want to bring into conversations more often?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "connect_149",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What would change if you trusted that connection doesn’t require perfect words?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "connect_150",
    planet: "connect",
    category: "relational_authenticity",
    prompt: "What does it mean to you to feel truly heard?",
    depth: "deep",
    skill: "relational_authenticity",
    challenge: "stretch",
    displayLevel: 5,
  },
];
