import type { HaeloPrompt } from "./types";

export const EXPLORE_PROMPTS: HaeloPrompt[] = [
  {
    id: "explore_001",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What have you been thinking about lately when nobody else is around?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_002",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What topic keeps pulling your attention back to it?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_003",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you’re curious about but haven’t explored yet?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_004",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What kind of problem do you naturally like trying to solve?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_005",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What kinds of questions do you find yourself asking?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_006",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you’ve recently realized you care about?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_007",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What activity makes time pass unusually quickly for you?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_008",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What kind of conversation energizes you?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_009",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What kind of conversation makes you lose interest?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_010",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you wish you understood better about yourself?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_011",
    planet: "explore",
    category: "self_curiosity",
    prompt: "When do you feel most mentally awake?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_012",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What makes you curious about another person?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_013",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you’ve changed your mind about recently?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_014",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What caused the change?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_015",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What is something you want to experience at least once?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_016",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What kind of challenge feels exciting rather than frightening?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_017",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What subject could you imagine becoming fascinated by if someone introduced it well?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_018",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you notice yourself returning to again and again?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_019",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s one question about life you don’t expect to have a simple answer to?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_020",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What part of growing up are you most curious about?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_021",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What do you think your curiosity says about you?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_022",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What’s something you would learn even if nobody graded you on it?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_023",
    planet: "explore",
    category: "self_curiosity",
    prompt: "If you had a completely free month, what would you explore?",
    depth: "light",
    skill: "self_curiosity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_024",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What do you want to understand better about other people?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_025",
    planet: "explore",
    category: "self_curiosity",
    prompt: "What do you want to understand better about yourself?",
    depth: "personal",
    skill: "self_curiosity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_026",
    planet: "explore",
    category: "values",
    prompt: "What quality do you respect most in another person?",
    depth: "light",
    skill: "values",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_027",
    planet: "explore",
    category: "values",
    prompt: "What behavior makes you lose respect for someone?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_028",
    planet: "explore",
    category: "values",
    prompt: "What does loyalty mean to you?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_029",
    planet: "explore",
    category: "values",
    prompt: "What does honesty mean when telling the full truth could hurt someone?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_030",
    planet: "explore",
    category: "values",
    prompt: "What makes something fair?",
    depth: "light",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_031",
    planet: "explore",
    category: "values",
    prompt: "What does kindness look like when it’s inconvenient?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_032",
    planet: "explore",
    category: "values",
    prompt: "What does courage mean to you?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_033",
    planet: "explore",
    category: "values",
    prompt: "What does independence mean to you?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_034",
    planet: "explore",
    category: "values",
    prompt: "What does success mean when nobody else is watching?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_035",
    planet: "explore",
    category: "values",
    prompt: "What makes someone trustworthy?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_036",
    planet: "explore",
    category: "values",
    prompt: "What makes someone a good friend?",
    depth: "light",
    skill: "values",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "explore_037",
    planet: "explore",
    category: "values",
    prompt: "What responsibility do you think people have toward strangers?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_038",
    planet: "explore",
    category: "values",
    prompt: "What responsibility do friends have toward one another?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_039",
    planet: "explore",
    category: "values",
    prompt: "When is ambition healthy?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_040",
    planet: "explore",
    category: "values",
    prompt: "What should never be sacrificed just to succeed?",
    depth: "personal",
    skill: "values",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_041",
    planet: "explore",
    category: "values",
    prompt: "Which matters more to you: being dependable or being flexible?",
    depth: "light",
    skill: "values",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_042",
    planet: "explore",
    category: "values",
    prompt: "When is breaking a rule justified?",
    depth: "personal",
    skill: "values",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_043",
    planet: "explore",
    category: "values",
    prompt: "What kind of person do you respect even if you don’t particularly like them?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_044",
    planet: "explore",
    category: "values",
    prompt: "What makes you feel proud of the way you handled something?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_045",
    planet: "explore",
    category: "values",
    prompt: "What kind of behavior makes you disappointed in yourself?",
    depth: "deep",
    skill: "values",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_046",
    planet: "explore",
    category: "values",
    prompt: "What principle do you want to remember when making difficult decisions?",
    depth: "deep",
    skill: "values",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_047",
    planet: "explore",
    category: "values",
    prompt: "What do you think people owe one another in a community?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_048",
    planet: "explore",
    category: "values",
    prompt: "What is one value you learned from your family?",
    depth: "personal",
    skill: "values",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_049",
    planet: "explore",
    category: "values",
    prompt: "What is one value you have chosen for yourself?",
    depth: "deep",
    skill: "values",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_050",
    planet: "explore",
    category: "values",
    prompt: "What do you want your choices to say about what matters to you?",
    depth: "deep",
    skill: "values",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_051",
    planet: "explore",
    category: "identity",
    prompt: "What are three things that feel important to who you are right now?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_052",
    planet: "explore",
    category: "identity",
    prompt: "Which parts of your identity feel chosen?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_053",
    planet: "explore",
    category: "identity",
    prompt: "Which parts feel like they were given to you?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_054",
    planet: "explore",
    category: "identity",
    prompt: "What role do you tend to play in your friend group?",
    depth: "light",
    skill: "identity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_055",
    planet: "explore",
    category: "identity",
    prompt: "Do you like that role?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_056",
    planet: "explore",
    category: "identity",
    prompt: "What role do you tend to play in your family?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_057",
    planet: "explore",
    category: "identity",
    prompt: "How is that different from who you are with friends?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_058",
    planet: "explore",
    category: "identity",
    prompt: "What part of yourself feels most stable?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_059",
    planet: "explore",
    category: "identity",
    prompt: "What part feels like it’s changing?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_060",
    planet: "explore",
    category: "identity",
    prompt: "What do people assume about you that isn’t quite accurate?",
    depth: "personal",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_061",
    planet: "explore",
    category: "identity",
    prompt: "What version of yourself appears when you feel completely comfortable?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_062",
    planet: "explore",
    category: "identity",
    prompt: "What version appears when you feel uncertain?",
    depth: "personal",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_063",
    planet: "explore",
    category: "identity",
    prompt: "How have you changed since you were younger?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_064",
    planet: "explore",
    category: "identity",
    prompt: "What about younger you is still very much present?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_065",
    planet: "explore",
    category: "identity",
    prompt: "What label do people use for you that feels incomplete?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_066",
    planet: "explore",
    category: "identity",
    prompt: "What is something you are that cannot be summarized by achievements?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_067",
    planet: "explore",
    category: "identity",
    prompt: "What qualities do you hope people associate with you?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_068",
    planet: "explore",
    category: "identity",
    prompt: "What qualities do you hope you never feel pressured to perform?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_069",
    planet: "explore",
    category: "identity",
    prompt: "Who are you when nobody expects anything from you?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_070",
    planet: "explore",
    category: "identity",
    prompt: "What part of yourself are you still learning how to describe?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_071",
    planet: "explore",
    category: "identity",
    prompt: "What’s a contradiction in your personality that you actually like?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_072",
    planet: "explore",
    category: "identity",
    prompt: "What makes you feel grounded in who you are?",
    depth: "personal",
    skill: "identity",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_073",
    planet: "explore",
    category: "identity",
    prompt: "What makes you question yourself?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_074",
    planet: "explore",
    category: "identity",
    prompt: "What would you want someone to understand before trying to define you?",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_075",
    planet: "explore",
    category: "identity",
    prompt: "Finish this thought: \"I’m becoming someone who…\"",
    depth: "deep",
    skill: "identity",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_076",
    planet: "explore",
    category: "perspective",
    prompt: "What belief did you have when you were younger that you no longer have?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_077",
    planet: "explore",
    category: "perspective",
    prompt: "What changed it?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_078",
    planet: "explore",
    category: "perspective",
    prompt: "When was the last time someone genuinely changed your mind?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_079",
    planet: "explore",
    category: "perspective",
    prompt: "What made their argument convincing?",
    depth: "light",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_080",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something you once judged that you understand better now?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_081",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something you used to care about a lot that matters less now?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_082",
    planet: "explore",
    category: "perspective",
    prompt: "What matters more to you now than it used to?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_083",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something your friends generally believe that you’re unsure about?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_084",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something adults generally believe that you’re unsure about?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_085",
    planet: "explore",
    category: "perspective",
    prompt: "What opinion are you deliberately keeping open?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_086",
    planet: "explore",
    category: "perspective",
    prompt: "What makes it difficult to admit when you’ve changed your mind?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_087",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something you’ve learned from someone very different from you?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_088",
    planet: "explore",
    category: "perspective",
    prompt: "What experience has shaped one of your strongest opinions?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_089",
    planet: "explore",
    category: "perspective",
    prompt: "What belief of yours has never really been tested?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_090",
    planet: "explore",
    category: "perspective",
    prompt: "What question could challenge that belief?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_091",
    planet: "explore",
    category: "perspective",
    prompt: "How do you decide whether information is trustworthy?",
    depth: "light",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_092",
    planet: "explore",
    category: "perspective",
    prompt: "How do you react when new information conflicts with what you already believe?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_093",
    planet: "explore",
    category: "perspective",
    prompt: "What opinion are you curious to hear the strongest argument against?",
    depth: "personal",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_094",
    planet: "explore",
    category: "perspective",
    prompt: "What’s something where you understand both sides?",
    depth: "light",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_095",
    planet: "explore",
    category: "perspective",
    prompt: "What issue do you think people oversimplify?",
    depth: "personal",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_096",
    planet: "explore",
    category: "perspective",
    prompt: "What is something you have more questions about than answers?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_097",
    planet: "explore",
    category: "perspective",
    prompt: "What makes uncertainty uncomfortable?",
    depth: "personal",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_098",
    planet: "explore",
    category: "perspective",
    prompt: "What can be useful about not having an answer yet?",
    depth: "personal",
    skill: "perspective",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_099",
    planet: "explore",
    category: "perspective",
    prompt: "When does confidence become stubbornness?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_100",
    planet: "explore",
    category: "perspective",
    prompt: "What is something you hope you are always willing to reconsider?",
    depth: "deep",
    skill: "perspective",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_101",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of person do you want to be a year from now?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_102",
    planet: "explore",
    category: "future_self",
    prompt: "What do you hope feels easier by then?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_103",
    planet: "explore",
    category: "future_self",
    prompt: "What do you hope still feels challenging because it means you’re growing?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_104",
    planet: "explore",
    category: "future_self",
    prompt: "What is something you want future you to thank you for?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_105",
    planet: "explore",
    category: "future_self",
    prompt: "What do you want to become more courageous about?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_106",
    planet: "explore",
    category: "future_self",
    prompt: "What do you want to become more curious about?",
    depth: "light",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_107",
    planet: "explore",
    category: "future_self",
    prompt: "What do you want to stop caring so much about?",
    depth: "personal",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "explore_108",
    planet: "explore",
    category: "future_self",
    prompt: "What do you want to care more deeply about?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_109",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of people do you want around you?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_110",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of friend do you want to become?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_111",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of student or learner do you want to become?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_112",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of communicator do you want to become?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_113",
    planet: "explore",
    category: "future_self",
    prompt: "What do you hope your life contains more of in five years?",
    depth: "light",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_114",
    planet: "explore",
    category: "future_self",
    prompt: "What do you hope it contains less of?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_115",
    planet: "explore",
    category: "future_self",
    prompt: "If you could try something without worrying whether you were naturally good at it, what would you try?",
    depth: "light",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "explore_116",
    planet: "explore",
    category: "future_self",
    prompt: "What’s a future you can imagine that genuinely excites you?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_117",
    planet: "explore",
    category: "future_self",
    prompt: "What’s a future other people might expect from you that you’re not sure you want?",
    depth: "deep",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_118",
    planet: "explore",
    category: "future_self",
    prompt: "What does independence look like in your future?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_119",
    planet: "explore",
    category: "future_self",
    prompt: "What does belonging look like?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_120",
    planet: "explore",
    category: "future_self",
    prompt: "What does meaningful work look like?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_121",
    planet: "explore",
    category: "future_self",
    prompt: "What kind of problems would you like to help solve?",
    depth: "personal",
    skill: "future_self",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_122",
    planet: "explore",
    category: "future_self",
    prompt: "What would you do differently if you weren’t trying to impress anyone?",
    depth: "deep",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_123",
    planet: "explore",
    category: "future_self",
    prompt: "What is one risk you hope you eventually become brave enough to take?",
    depth: "deep",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_124",
    planet: "explore",
    category: "future_self",
    prompt: "What do you want your future decisions to be guided by?",
    depth: "deep",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_125",
    planet: "explore",
    category: "future_self",
    prompt: "What voice do you want future you to have?",
    depth: "deep",
    skill: "future_self",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "explore_126",
    planet: "explore",
    category: "meaning",
    prompt: "What makes a day feel meaningful to you?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_127",
    planet: "explore",
    category: "meaning",
    prompt: "What makes something worth working hard for?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_128",
    planet: "explore",
    category: "meaning",
    prompt: "What makes a friendship meaningful rather than just convenient?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_129",
    planet: "explore",
    category: "meaning",
    prompt: "What experience has taught you something you still think about?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_130",
    planet: "explore",
    category: "meaning",
    prompt: "What is something difficult that helped you understand yourself better?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_131",
    planet: "explore",
    category: "meaning",
    prompt: "What does a \"good life\" mean to you right now?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_132",
    planet: "explore",
    category: "meaning",
    prompt: "What do you think people spend too much time chasing?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_133",
    planet: "explore",
    category: "meaning",
    prompt: "What do you think people don’t spend enough time appreciating?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_134",
    planet: "explore",
    category: "meaning",
    prompt: "What makes an achievement actually feel satisfying?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_135",
    planet: "explore",
    category: "meaning",
    prompt: "What makes an achievement feel strangely empty?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_136",
    planet: "explore",
    category: "meaning",
    prompt: "What do you want to be able to say you stood for?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "explore_137",
    planet: "explore",
    category: "meaning",
    prompt: "What makes a decision feel right even when it’s difficult?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_138",
    planet: "explore",
    category: "meaning",
    prompt: "What tells you that something isn’t right for you?",
    depth: "personal",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_139",
    planet: "explore",
    category: "meaning",
    prompt: "What is something you want to trust yourself about more?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_140",
    planet: "explore",
    category: "meaning",
    prompt: "Who has shaped the way you think, and how?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_141",
    planet: "explore",
    category: "meaning",
    prompt: "What experience has shaped the way you see yourself?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_142",
    planet: "explore",
    category: "meaning",
    prompt: "What do you want to remember when you feel pressure to become someone else?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "explore_143",
    planet: "explore",
    category: "meaning",
    prompt: "What matters enough to you that you would protect time for it?",
    depth: "personal",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_144",
    planet: "explore",
    category: "meaning",
    prompt: "What makes you feel connected to something bigger than your immediate worries?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_145",
    planet: "explore",
    category: "meaning",
    prompt: "What do you think deserves more of your attention?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_146",
    planet: "explore",
    category: "meaning",
    prompt: "What do you think deserves less?",
    depth: "personal",
    skill: "meaning",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "explore_147",
    planet: "explore",
    category: "meaning",
    prompt: "What do you hope people understand about what matters to you?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "explore_148",
    planet: "explore",
    category: "meaning",
    prompt: "What question do you think you’ll still be asking yourself years from now?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "explore_149",
    planet: "explore",
    category: "meaning",
    prompt: "What answer about yourself are you currently growing into?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "explore_150",
    planet: "explore",
    category: "meaning",
    prompt: "If you could understand one thing more clearly about yourself right now, what would it be?",
    depth: "deep",
    skill: "meaning",
    challenge: "stretch",
    displayLevel: 5,
  },
];
