import type { HaeloPrompt } from "./types";

export const EXPRESS_PROMPTS: HaeloPrompt[] = [
  {
    id: "express_001",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you could talk about for ten minutes without preparing?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_002",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you’ve been excited about lately that you haven’t gotten to explain to anyone?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_003",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s a small thing that made your day better recently?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_004",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you wish people asked you about more often?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_005",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s a topic you always have an opinion about?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_006",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you’ve discovered recently that you want other people to know about?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_007",
    planet: "express",
    category: "getting_comfortable",
    prompt: "Tell the story of something unexpectedly funny that happened to you.",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_008",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you love that you think deserves more appreciation?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_009",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s one thing you could teach someone else?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_010",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you’ve been thinking about more than usual lately?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_011",
    planet: "express",
    category: "getting_comfortable",
    prompt: "Describe something you enjoy in a way that would make someone else understand why you love it.",
    depth: "light",
    skill: "specificity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_012",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s one part of your day you usually look forward to?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_013",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you’re currently curious about?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_014",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s one thing you’ve gotten much better at over the past year?",
    depth: "personal",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_015",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you wish you had more opportunities to talk about?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_016",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s one ordinary thing you find surprisingly interesting?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_017",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you recently learned about yourself?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_018",
    planet: "express",
    category: "getting_comfortable",
    prompt: "Describe a place where you feel comfortable being yourself.",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_019",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you could happily spend an entire afternoon doing?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_020",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you care about that other people might think is unimportant?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_021",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s a recent conversation you really enjoyed, and why?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_022",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something you notice that you think other people often miss?",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_023",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s a small opinion you have that you feel strangely strongly about?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_024",
    planet: "express",
    category: "getting_comfortable",
    prompt: "What’s something that instantly puts you in a better mood?",
    depth: "light",
    skill: "free_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_025",
    planet: "express",
    category: "getting_comfortable",
    prompt: "If someone wanted to understand you better, what topic should they ask you about?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_026",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a recent moment when you felt genuinely proud of yourself.",
    depth: "personal",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_027",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a moment this week that felt different from what you expected.",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_028",
    planet: "express",
    category: "specific_expression",
    prompt: "What’s something people often describe as \"fun\" that you personally experience in a more complicated way?",
    depth: "personal",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_029",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe the difference between a good day and a great day for you.",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_030",
    planet: "express",
    category: "specific_expression",
    prompt: "What does feeling comfortable around someone actually look like for you?",
    depth: "personal",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_031",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a moment when you felt completely absorbed in what you were doing.",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_032",
    planet: "express",
    category: "specific_expression",
    prompt: "What does boredom feel like to you?",
    depth: "light",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_033",
    planet: "express",
    category: "specific_expression",
    prompt: "What does excitement feel like before you even say anything?",
    depth: "light",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_034",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe someone’s personality without using words like nice, funny, smart, or cool.",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_035",
    planet: "express",
    category: "specific_expression",
    prompt: "What makes a conversation feel genuinely interesting to you?",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_036",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a moment when you felt understood.",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_037",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a moment when someone surprised you in a good way.",
    depth: "personal",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_038",
    planet: "express",
    category: "specific_expression",
    prompt: "What makes a place feel welcoming to you?",
    depth: "light",
    skill: "specificity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_039",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe something that annoys you without using the word annoying.",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_040",
    planet: "express",
    category: "specific_expression",
    prompt: "What does confidence look like in someone you admire?",
    depth: "personal",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_041",
    planet: "express",
    category: "specific_expression",
    prompt: "What makes you feel like you can relax around another person?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_042",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe the feeling of finally understanding something that confused you for a long time.",
    depth: "light",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_043",
    planet: "express",
    category: "specific_expression",
    prompt: "What makes an ordinary moment memorable?",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_044",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe something beautiful that you noticed recently.",
    depth: "light",
    skill: "specificity",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_045",
    planet: "express",
    category: "specific_expression",
    prompt: "What does it feel like when you know exactly what you want to say?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_046",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe the difference between being alone and feeling lonely.",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_047",
    planet: "express",
    category: "specific_expression",
    prompt: "What makes someone interesting to talk to?",
    depth: "light",
    skill: "specificity",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_048",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a moment that felt much bigger to you than it probably looked from the outside.",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_049",
    planet: "express",
    category: "specific_expression",
    prompt: "What does it feel like when you’re trying not to show that something matters to you?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_050",
    planet: "express",
    category: "specific_expression",
    prompt: "Describe a feeling that is difficult for you to explain.",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_051",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something that has made you feel genuinely happy recently?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "beginner",
    displayLevel: 2,
  },
  {
    id: "express_052",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you’ve been looking forward to?",
    depth: "light",
    skill: "emotional_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_053",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something that disappointed you more than you expected?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_054",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something that made you nervous but that you did anyway?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_055",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you’ve felt proud of but didn’t really tell anyone?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_056",
    planet: "express",
    category: "emotional_expression",
    prompt: "When do you feel most appreciated?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_057",
    planet: "express",
    category: "emotional_expression",
    prompt: "What kind of situation makes you feel left out?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_058",
    planet: "express",
    category: "emotional_expression",
    prompt: "What makes you feel respected?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_059",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you sometimes pretend doesn’t bother you even though it does?",
    depth: "deep",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_060",
    planet: "express",
    category: "emotional_expression",
    prompt: "When do you feel most comfortable speaking freely?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_061",
    planet: "express",
    category: "emotional_expression",
    prompt: "What kind of compliment actually means something to you?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "beginner",
    displayLevel: 2,
  },
  {
    id: "express_062",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something that recently made you feel relieved?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "beginner",
    displayLevel: 2,
  },
  {
    id: "express_063",
    planet: "express",
    category: "emotional_expression",
    prompt: "What makes you feel genuinely supported by someone?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_064",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something that can make you feel self-conscious?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_065",
    planet: "express",
    category: "emotional_expression",
    prompt: "What makes you feel energized?",
    depth: "light",
    skill: "emotional_expression",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "express_066",
    planet: "express",
    category: "emotional_expression",
    prompt: "What makes you feel drained even when nothing obviously bad happened?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_067",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you wish people understood about how you react to things?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_068",
    planet: "express",
    category: "emotional_expression",
    prompt: "When do you feel most confident being yourself?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_069",
    planet: "express",
    category: "emotional_expression",
    prompt: "What kind of misunderstanding frustrates you most?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_070",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you’re grateful for that you rarely say out loud?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_071",
    planet: "express",
    category: "emotional_expression",
    prompt: "What emotion do you think you’re especially good at recognizing in yourself?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_072",
    planet: "express",
    category: "emotional_expression",
    prompt: "What emotion is harder for you to put into words?",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_073",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you care about enough that criticism of it feels personal?",
    depth: "deep",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_074",
    planet: "express",
    category: "emotional_expression",
    prompt: "Describe a moment when you felt two different emotions at once.",
    depth: "personal",
    skill: "emotional_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_075",
    planet: "express",
    category: "emotional_expression",
    prompt: "What’s something you wish you were better at explaining when you’re upset?",
    depth: "deep",
    skill: "emotional_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_076",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something about you that people usually don’t notice right away?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_077",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something people sometimes misunderstand about you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_078",
    planet: "express",
    category: "self_disclosure",
    prompt: "What side of your personality comes out only around people you trust?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_079",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you wish your friends understood better about you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_080",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you wish adults understood better about you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_081",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you care about more deeply than people might assume?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_082",
    planet: "express",
    category: "self_disclosure",
    prompt: "What part of your personality took you a while to appreciate?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_083",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you’re still figuring out about yourself?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_084",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you used to hide or downplay that you’re more comfortable with now?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_085",
    planet: "express",
    category: "self_disclosure",
    prompt: "When do you feel most like yourself?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_086",
    planet: "express",
    category: "self_disclosure",
    prompt: "When do you feel least like yourself?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_087",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you want people to remember about you after spending time with you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_088",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s a quality you value in yourself that doesn’t show up on a résumé or report card?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_089",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you wish you could explain about yourself without worrying how it would sound?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_090",
    planet: "express",
    category: "self_disclosure",
    prompt: "What part of yourself do you think deserves more attention?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_091",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you’ve become more comfortable admitting?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_092",
    planet: "express",
    category: "self_disclosure",
    prompt: "What do you wish people knew before making assumptions about you?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_093",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s one contradiction about yourself that actually makes sense to you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_094",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you’re much more sensitive about than people realize?",
    depth: "deep",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_095",
    planet: "express",
    category: "self_disclosure",
    prompt: "What brings out the most playful version of you?",
    depth: "light",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_096",
    planet: "express",
    category: "self_disclosure",
    prompt: "What brings out the most serious version of you?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "express_097",
    planet: "express",
    category: "self_disclosure",
    prompt: "What do you think people hear differently when you say it versus when someone else says it?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_098",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you want to become more comfortable talking about?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_099",
    planet: "express",
    category: "self_disclosure",
    prompt: "What part of your personality do you hope never changes?",
    depth: "personal",
    skill: "self_disclosure",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_100",
    planet: "express",
    category: "self_disclosure",
    prompt: "What’s something you’re learning to say without feeling like you need to justify it?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_101",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you’ve wanted to tell someone but haven’t found the right words for?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_102",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s a thank-you you’ve thought about but never actually said?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_103",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you had said in a past conversation?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_104",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish people asked before assuming?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_105",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What opinion do you sometimes keep to yourself because explaining it feels exhausting?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_106",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say more easily when someone asks, \"Are you okay?\"",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_107",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could explain better to your family?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_108",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could explain better to your friends?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_109",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say to a teacher or coach?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "express_110",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say without worrying about sounding dramatic?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_111",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you appreciate about someone that you don’t tell them enough?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_112",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could ask for more easily?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_113",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you need space?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_114",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you want someone to stay?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_115",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you don’t understand something?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_116",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you feel overlooked?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_117",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you disagree but don’t want an argument?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_118",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you’re proud of yourself?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_119",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say when you change your mind?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_120",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could say without adding \"sorry\" first?",
    depth: "personal",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_121",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you wish you could explain about how you want to be treated?",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_122",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you would say more often if you knew nobody would judge the wording?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_123",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you’re ready to stop pretending you don’t care about?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_124",
    planet: "express",
    category: "unsaid_expression",
    prompt: "What’s something you want to get better at saying directly?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_125",
    planet: "express",
    category: "unsaid_expression",
    prompt: "Finish this thought out loud: \"Something I’ve been meaning to say is…\"",
    depth: "deep",
    skill: "unsaid_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_126",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s an idea you want to express without first worrying whether everyone will agree?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_127",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you believe you deserve to be able to say openly?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_128",
    planet: "express",
    category: "owning_expression",
    prompt: "What is something about your personality that you no longer want to shrink?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_129",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s one thing you want to express more confidently this year?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_130",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you want to stop editing out of yourself?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_131",
    planet: "express",
    category: "owning_expression",
    prompt: "If you could speak without worrying about sounding impressive, what would you talk about?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_132",
    planet: "express",
    category: "owning_expression",
    prompt: "What do you sound like when you’re not trying to manage someone else’s reaction?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_133",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you want to say more clearly instead of hinting at it?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_134",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you want to become more comfortable admitting you care about?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_135",
    planet: "express",
    category: "owning_expression",
    prompt: "What would \"using your voice\" mean for you personally?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_136",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s one way you want your communication to feel different six months from now?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_137",
    planet: "express",
    category: "owning_expression",
    prompt: "When have you surprised yourself by speaking more openly than usual?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_138",
    planet: "express",
    category: "owning_expression",
    prompt: "What helped you do that?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_139",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you used to struggle to say that feels easier now?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_140",
    planet: "express",
    category: "owning_expression",
    prompt: "What part of your voice do you think is already strong?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_141",
    planet: "express",
    category: "owning_expression",
    prompt: "What part of your voice do you want to use more often?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_142",
    planet: "express",
    category: "owning_expression",
    prompt: "What would you say if you trusted that your perspective was worth hearing?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_143",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s something you want to be known for expressing honestly?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_144",
    planet: "express",
    category: "owning_expression",
    prompt: "What does being authentic sound like to you?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_145",
    planet: "express",
    category: "owning_expression",
    prompt: "What’s one sentence you want to become more comfortable saying?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_146",
    planet: "express",
    category: "owning_expression",
    prompt: "How would you describe the difference between your \"edited\" voice and your natural voice?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_147",
    planet: "express",
    category: "owning_expression",
    prompt: "What helps you stop overthinking your words?",
    depth: "personal",
    skill: "authentic_expression",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "express_148",
    planet: "express",
    category: "owning_expression",
    prompt: "What do you want someone listening to you to understand—not just hear?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "express_149",
    planet: "express",
    category: "owning_expression",
    prompt: "What would it look like to take up a little more conversational space?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "express_150",
    planet: "express",
    category: "owning_expression",
    prompt: "If your voice felt completely yours, what would be different?",
    depth: "deep",
    skill: "authentic_expression",
    challenge: "stretch",
    displayLevel: 5,
  },
];
