import type { HaeloPrompt } from "./types";

export const STAND_PROMPTS: HaeloPrompt[] = [
  {
    id: "stand_001",
    planet: "stand",
    category: "opinions",
    prompt: "What’s a school rule you would change, and why?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_002",
    planet: "stand",
    category: "opinions",
    prompt: "What’s something people your age are expected to care about that you think is overrated?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_003",
    planet: "stand",
    category: "opinions",
    prompt: "What’s something adults often get wrong about teenagers?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_004",
    planet: "stand",
    category: "opinions",
    prompt: "Should students have homework every night? Defend your answer.",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_005",
    planet: "stand",
    category: "opinions",
    prompt: "What makes someone a good leader?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_006",
    planet: "stand",
    category: "opinions",
    prompt: "Should people always forgive someone who apologizes?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_007",
    planet: "stand",
    category: "opinions",
    prompt: "Is being honest always more important than being polite?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_008",
    planet: "stand",
    category: "opinions",
    prompt: "What makes a friendship worth keeping?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_009",
    planet: "stand",
    category: "opinions",
    prompt: "Should schools care more about effort or results?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_010",
    planet: "stand",
    category: "opinions",
    prompt: "What’s one thing social media improves and one thing it makes worse?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_011",
    planet: "stand",
    category: "opinions",
    prompt: "Should people be expected to explain why they say no?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_012",
    planet: "stand",
    category: "opinions",
    prompt: "What makes an apology genuine?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_013",
    planet: "stand",
    category: "opinions",
    prompt: "Is it better to be very ambitious or very balanced?",
    depth: "light",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_014",
    planet: "stand",
    category: "opinions",
    prompt: "What should matter more when choosing friends: similarity or difference?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_015",
    planet: "stand",
    category: "opinions",
    prompt: "What’s something society treats as important that you don’t think matters very much?",
    depth: "light",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_016",
    planet: "stand",
    category: "opinions",
    prompt: "What should schools teach that they usually don’t?",
    depth: "light",
    skill: "opinion",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_017",
    planet: "stand",
    category: "opinions",
    prompt: "When does competition help people, and when does it hurt?",
    depth: "light",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_018",
    planet: "stand",
    category: "opinions",
    prompt: "Is it more important to be liked or respected?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_019",
    planet: "stand",
    category: "opinions",
    prompt: "What does someone have to do to earn your trust?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_020",
    planet: "stand",
    category: "opinions",
    prompt: "Should people speak up when a joke makes them uncomfortable even if everyone else is laughing?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_021",
    planet: "stand",
    category: "opinions",
    prompt: "What does fairness actually mean to you?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_022",
    planet: "stand",
    category: "opinions",
    prompt: "When is changing your mind a strength?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_023",
    planet: "stand",
    category: "opinions",
    prompt: "Should loyalty ever have limits?",
    depth: "personal",
    skill: "opinion",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_024",
    planet: "stand",
    category: "opinions",
    prompt: "What responsibility do people have when they see someone being treated unfairly?",
    depth: "personal",
    skill: "opinion",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_025",
    planet: "stand",
    category: "opinions",
    prompt: "What’s one belief you hold strongly enough that you would defend it even if the room disagreed?",
    depth: "personal",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_026",
    planet: "stand",
    category: "disagreement",
    prompt: "Your friend loves a movie you hated. Explain why you disagree without pretending to agree.",
    depth: "light",
    skill: "disagreement",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_027",
    planet: "stand",
    category: "disagreement",
    prompt: "Someone says your favorite hobby is pointless. Respond.",
    depth: "light",
    skill: "disagreement",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_028",
    planet: "stand",
    category: "disagreement",
    prompt: "A classmate says an idea you care about is stupid. What would you say?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_029",
    planet: "stand",
    category: "disagreement",
    prompt: "Someone confidently states something you believe is wrong. How would you enter the conversation?",
    depth: "light",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_030",
    planet: "stand",
    category: "disagreement",
    prompt: "Your whole group wants one thing and you want something different. State your preference.",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_031",
    planet: "stand",
    category: "disagreement",
    prompt: "A friend says, \"Everyone thinks this.\" You don’t. Respond.",
    depth: "light",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_032",
    planet: "stand",
    category: "disagreement",
    prompt: "Someone interrupts you while you’re explaining your opinion. What do you say?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_033",
    planet: "stand",
    category: "disagreement",
    prompt: "Someone says, \"You’re overthinking it.\" You think the issue matters. Respond.",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_034",
    planet: "stand",
    category: "disagreement",
    prompt: "A friend disagrees with you and starts getting louder. How do you hold your position without matching their tone?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_035",
    planet: "stand",
    category: "disagreement",
    prompt: "Someone says, \"It’s not that serious.\" You think it is. What would you say?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_036",
    planet: "stand",
    category: "disagreement",
    prompt: "How would you disagree with someone you really admire?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_037",
    planet: "stand",
    category: "disagreement",
    prompt: "How would you disagree with someone who is older than you?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_038",
    planet: "stand",
    category: "disagreement",
    prompt: "How would you disagree with your closest friend?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_039",
    planet: "stand",
    category: "disagreement",
    prompt: "How would you disagree when you’re not 100% certain but still have a perspective?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_040",
    planet: "stand",
    category: "disagreement",
    prompt: "Practice saying: \"I understand why you see it that way, but…,\" and complete the thought.",
    depth: "light",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_041",
    planet: "stand",
    category: "disagreement",
    prompt: "Describe a disagreement where both sides could have reasonable points.",
    depth: "light",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_042",
    planet: "stand",
    category: "disagreement",
    prompt: "What’s the difference between respecting someone and agreeing with them?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_043",
    planet: "stand",
    category: "disagreement",
    prompt: "When have you changed your mind because someone disagreed with you well?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_044",
    planet: "stand",
    category: "disagreement",
    prompt: "What makes disagreement feel safe?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_045",
    planet: "stand",
    category: "disagreement",
    prompt: "What makes disagreement feel intimidating?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_046",
    planet: "stand",
    category: "disagreement",
    prompt: "What helps you keep talking when someone challenges your opinion?",
    depth: "personal",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_047",
    planet: "stand",
    category: "disagreement",
    prompt: "How can you make your point without insulting someone else’s?",
    depth: "light",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_048",
    planet: "stand",
    category: "disagreement",
    prompt: "When is it worth continuing a disagreement?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_049",
    planet: "stand",
    category: "disagreement",
    prompt: "When is it better to say, \"We probably aren’t going to agree\"?",
    depth: "personal",
    skill: "disagreement",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_050",
    planet: "stand",
    category: "disagreement",
    prompt: "What would it sound like for you to disagree without apologizing for disagreeing?",
    depth: "deep",
    skill: "disagreement",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_051",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a teacher for clarification on something you genuinely don’t understand.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_052",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a friend to stop doing something that distracts you.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_053",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to give you more time to think before answering.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_054",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a group to include your idea instead of immediately going with someone else’s.",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_055",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to repeat themselves because you didn’t hear them.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_056",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a teacher to reconsider something you think was graded unfairly.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_057",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a friend for help with something you normally try to handle alone.",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_058",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask your family for more privacy.",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_059",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask for more information before agreeing to a plan.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_060",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to give you credit for work you contributed.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_061",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask to change plans when something no longer works for you.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_062",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone not to share something you told them privately.",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_063",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask to finish what you were saying after being interrupted.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_064",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to slow down because you need more time to process.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_065",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask for a different role in a group project.",
    depth: "light",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_066",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone directly whether something is wrong instead of guessing.",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_067",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask a friend to listen before giving advice.",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_068",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask for feedback on something you care about.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_069",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to explain what they meant instead of assuming.",
    depth: "light",
    skill: "asking_for_needs",
    challenge: "beginner",
    displayLevel: 1,
  },
  {
    id: "stand_070",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask to be included in a decision that affects you.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_071",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone for space without making it sound like you’re angry at them.",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_072",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask someone to stop teasing you about something you don’t find funny.",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_073",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask for an opportunity you want even if you’re not sure you’ll get it.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_074",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "Ask to revisit a conversation that ended badly.",
    depth: "deep",
    skill: "asking_for_needs",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_075",
    planet: "stand",
    category: "asking_for_needs",
    prompt: "What is something you currently wish you could ask for more directly?",
    depth: "deep",
    skill: "asking_for_needs",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_076",
    planet: "stand",
    category: "boundaries",
    prompt: "A friend keeps reading your messages over your shoulder. What would you say?",
    depth: "light",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_077",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone pressures you to share something personal. Respond.",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_078",
    planet: "stand",
    category: "boundaries",
    prompt: "A friend keeps making a joke you’ve said you dislike. What do you say next?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_079",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone wants an immediate answer and you need time. Respond.",
    depth: "light",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_080",
    planet: "stand",
    category: "boundaries",
    prompt: "A friend keeps asking why you can’t hang out. Practice saying no without inventing an excuse.",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_081",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone wants to borrow something you don’t want to lend. Respond.",
    depth: "light",
    skill: "boundaries",
    challenge: "beginner",
    displayLevel: 2,
  },
  {
    id: "stand_082",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone shares a photo of you that you don’t like. What would you say?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_083",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone keeps interrupting your alone time. Set a boundary.",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_084",
    planet: "stand",
    category: "boundaries",
    prompt: "A friend expects you to always respond immediately. What would you say?",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_085",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone tries to involve you in an argument that isn’t yours. Respond.",
    depth: "light",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_086",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone keeps asking a question you don’t want to answer. What would you say?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_087",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone makes a comment about your appearance that makes you uncomfortable. Respond.",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_088",
    planet: "stand",
    category: "boundaries",
    prompt: "A friend assumes you’ll do them a favor you never agreed to. What do you say?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_089",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone tells you that setting a boundary means you’re being rude. Respond.",
    depth: "deep",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_090",
    planet: "stand",
    category: "boundaries",
    prompt: "Someone pressures you to change your answer after you already said no.",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_091",
    planet: "stand",
    category: "boundaries",
    prompt: "What makes saying no difficult for you?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_092",
    planet: "stand",
    category: "boundaries",
    prompt: "What helps a \"no\" feel respectful but firm?",
    depth: "light",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_093",
    planet: "stand",
    category: "boundaries",
    prompt: "What’s the difference between being kind and always saying yes?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_094",
    planet: "stand",
    category: "boundaries",
    prompt: "When do you think explanations are helpful after setting a boundary?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_095",
    planet: "stand",
    category: "boundaries",
    prompt: "When should \"I don’t want to\" be enough?",
    depth: "deep",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_096",
    planet: "stand",
    category: "boundaries",
    prompt: "What boundary do you think teenagers deserve that adults sometimes overlook?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_097",
    planet: "stand",
    category: "boundaries",
    prompt: "How would you respond if someone you care about is disappointed by your boundary?",
    depth: "deep",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_098",
    planet: "stand",
    category: "boundaries",
    prompt: "What’s a boundary you admire when other people set it?",
    depth: "personal",
    skill: "boundaries",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_099",
    planet: "stand",
    category: "boundaries",
    prompt: "What does respecting your own limits sound like?",
    depth: "deep",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_100",
    planet: "stand",
    category: "boundaries",
    prompt: "Finish this sentence in a firm but respectful way: \"I’m not comfortable with…\"",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 3,
  },
  {
    id: "stand_101",
    planet: "stand",
    category: "self_advocacy",
    prompt: "A teacher misunderstands something you did. Explain your side clearly.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_102",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone takes credit for your idea. How would you address it?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_103",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You’re being left out of a conversation that directly involves you. Speak up.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_104",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You believe you deserve an opportunity but haven’t been considered. Make your case.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_105",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone assumes you don’t know much about a topic you actually understand well. Respond.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_106",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You receive feedback you think is unfair. How would you discuss it?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_107",
    planet: "stand",
    category: "self_advocacy",
    prompt: "A group keeps giving you the least interesting tasks. Speak up.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_108",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone repeatedly pronounces your name incorrectly after you’ve corrected them. What would you say?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_109",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You’re uncomfortable with how someone spoke to you. Address it.",
    depth: "deep",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_110",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You need an accommodation or adjustment to do your best work. Ask for it.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_111",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone makes a decision for you without asking. Respond.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_112",
    planet: "stand",
    category: "self_advocacy",
    prompt: "You are blamed for something that wasn’t entirely your responsibility. Explain your perspective.",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_113",
    planet: "stand",
    category: "self_advocacy",
    prompt: "A friend says, \"You never said anything before.\" Explain why something still needs to change.",
    depth: "deep",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_114",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone tells you that you’re being \"too sensitive.\" Respond without abandoning your point.",
    depth: "deep",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_115",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Someone assumes that because you’re quiet, you don’t have an opinion. What would you say?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_116",
    planet: "stand",
    category: "self_advocacy",
    prompt: "How would you advocate for someone else without speaking over them?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_117",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What makes you more willing to advocate for someone else than yourself?",
    depth: "deep",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_118",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What is one situation where you wish you had spoken up sooner?",
    depth: "deep",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_119",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What could you say if a similar situation happened again?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_120",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What is something you deserve to have a say in?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_121",
    planet: "stand",
    category: "self_advocacy",
    prompt: "How do you want people to respond when you speak up for yourself?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_122",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What is the difference between demanding something and advocating for yourself?",
    depth: "light",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 2,
  },
  {
    id: "stand_123",
    planet: "stand",
    category: "self_advocacy",
    prompt: "When has speaking up made a situation better?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_124",
    planet: "stand",
    category: "self_advocacy",
    prompt: "What would make it easier for you to advocate for yourself?",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_125",
    planet: "stand",
    category: "self_advocacy",
    prompt: "Finish the sentence: \"I want to make sure my perspective is part of this because…\"",
    depth: "personal",
    skill: "self_advocacy",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_126",
    planet: "stand",
    category: "conviction",
    prompt: "What belief would you defend even if it made you temporarily unpopular?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "stand_127",
    planet: "stand",
    category: "conviction",
    prompt: "When is it worth being the only person in the room who says something?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_128",
    planet: "stand",
    category: "conviction",
    prompt: "What makes someone courageous in conversation?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_129",
    planet: "stand",
    category: "conviction",
    prompt: "What do you want to become less afraid of saying?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_130",
    planet: "stand",
    category: "conviction",
    prompt: "What’s something you want to stop automatically apologizing for?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_131",
    planet: "stand",
    category: "conviction",
    prompt: "What do you want to be able to say even when your voice shakes?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "stand_132",
    planet: "stand",
    category: "conviction",
    prompt: "When is staying silent actually the stronger choice?",
    depth: "personal",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_133",
    planet: "stand",
    category: "conviction",
    prompt: "When does silence become avoidance?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_134",
    planet: "stand",
    category: "conviction",
    prompt: "What helps you trust your own judgment?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_135",
    planet: "stand",
    category: "conviction",
    prompt: "What’s one opinion you’ve become more willing to express over time?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_136",
    planet: "stand",
    category: "conviction",
    prompt: "What happened that made it easier?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_137",
    planet: "stand",
    category: "conviction",
    prompt: "What’s one boundary you want to become more confident setting?",
    depth: "personal",
    skill: "boundaries",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_138",
    planet: "stand",
    category: "conviction",
    prompt: "What’s one request you want to become more comfortable making?",
    depth: "personal",
    skill: "asking_for_needs",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_139",
    planet: "stand",
    category: "conviction",
    prompt: "What would standing up for yourself look like without becoming someone you’re not?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "stand_140",
    planet: "stand",
    category: "conviction",
    prompt: "Who do you know who disagrees confidently without being disrespectful? What do they do well?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_141",
    planet: "stand",
    category: "conviction",
    prompt: "What does \"holding your ground\" mean to you?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_142",
    planet: "stand",
    category: "conviction",
    prompt: "What is something you can say firmly while still leaving room to learn?",
    depth: "personal",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_143",
    planet: "stand",
    category: "conviction",
    prompt: "How do you want to respond when someone challenges you unexpectedly?",
    depth: "personal",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_144",
    planet: "stand",
    category: "conviction",
    prompt: "What’s something you’ve learned that makes your perspective worth trusting?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_145",
    planet: "stand",
    category: "conviction",
    prompt: "When have you regretted not speaking up?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_146",
    planet: "stand",
    category: "conviction",
    prompt: "When have you been glad you did speak up?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_147",
    planet: "stand",
    category: "conviction",
    prompt: "What would it feel like to know disagreement doesn’t automatically mean rejection?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 5,
  },
  {
    id: "stand_148",
    planet: "stand",
    category: "conviction",
    prompt: "What part of speaking up feels hardest: starting, explaining, or staying with your point?",
    depth: "personal",
    skill: "conviction",
    challenge: "developing",
    displayLevel: 3,
  },
  {
    id: "stand_149",
    planet: "stand",
    category: "conviction",
    prompt: "What would you like that part to feel like instead?",
    depth: "personal",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 4,
  },
  {
    id: "stand_150",
    planet: "stand",
    category: "conviction",
    prompt: "If you trusted that your voice belonged in the room, what would you say more often?",
    depth: "deep",
    skill: "conviction",
    challenge: "stretch",
    displayLevel: 5,
  },
];
