import type { BankQuestion } from "@/lib/questions/types";

export const CONFIDENCE_QUESTIONS: BankQuestion[] = [
  { id: "confidence-001", topicId: "confidence", text: "When do you feel most like yourself when you speak?" },
  { id: "confidence-002", topicId: "confidence", text: "Talk about a time you spoke up even though it was scary." },
  { id: "confidence-003", topicId: "confidence", text: "What does self-belief sound like in your head on a good day?" },
  { id: "confidence-004", topicId: "confidence", text: "Describe doubt—and how you move through it." },
  { id: "confidence-005", topicId: "confidence", text: "How do you handle comparison to others?" },
  { id: "confidence-006", topicId: "confidence", text: "Talk about presence—feeling grounded in a room." },
  { id: "confidence-007", topicId: "confidence", text: "What’s a compliment you struggle to accept?" },
  { id: "confidence-008", topicId: "confidence", text: "Describe preparing to be seen—presentation, performance, or post." },
  { id: "confidence-009", topicId: "confidence", text: "When does your voice get smaller?" },
  { id: "confidence-010", topicId: "confidence", text: "How do you rebuild confidence after embarrassment?" },
  { id: "confidence-011", topicId: "confidence", text: "Talk about courage that didn’t look dramatic." },
  { id: "confidence-012", topicId: "confidence", text: "What’s something you’re better at than you admit?" },
  { id: "confidence-013", topicId: "confidence", text: "Describe taking up space kindly." },
  { id: "confidence-014", topicId: "confidence", text: "When do you trust your own judgment?" },
  { id: "confidence-015", topicId: "confidence", text: "How does confidence show in your body language?" },
  { id: "confidence-016", topicId: "confidence", text: "Talk about impostor feelings in a setting you care about." },
  { id: "confidence-017", topicId: "confidence", text: "What’s a risk that grew your confidence?" },
  { id: "confidence-018", topicId: "confidence", text: "Describe mentoring or encouraging someone else." },
  { id: "confidence-019", topicId: "confidence", text: "When do achievements feel hollow—and when do they land?" },
  { id: "confidence-020", topicId: "confidence", text: "How do you talk to yourself after a mistake?" },
  { id: "confidence-021", topicId: "confidence", text: "Talk about being underestimated." },
  { id: "confidence-022", topicId: "confidence", text: "What’s changing about your confidence this year?" },
  { id: "confidence-023", topicId: "confidence", text: "Describe a role where you felt capable." },
  { id: "confidence-024", topicId: "confidence", text: "When is quiet confidence stronger than loud confidence?" },
  { id: "confidence-025", topicId: "confidence", text: "How do you ask for opportunities without shrinking?" },
  { id: "confidence-026", topicId: "confidence", text: "Talk about authenticity versus performing for approval." },
  { id: "confidence-027", topicId: "confidence", text: "What’s a boundary that increased your self-respect?" },
  { id: "confidence-028", topicId: "confidence", text: "Describe walking into a room as the new person." },
  { id: "confidence-029", topicId: "confidence", text: "When do you feel proud of how you handled something?" },
  { id: "confidence-030", topicId: "confidence", text: "How does social media affect your self-view?" },
  { id: "confidence-031", topicId: "confidence", text: "Talk about skills versus worth—keeping them separate." },
  { id: "confidence-032", topicId: "confidence", text: "What’s hard about receiving attention?" },
  { id: "confidence-033", topicId: "confidence", text: "Describe a time you advocated for yourself." },
  { id: "confidence-034", topicId: "confidence", text: "When do you need external validation—and when don’t you?" },
  { id: "confidence-035", topicId: "confidence", text: "How do you practice speaking with more ease?" },
  { id: "confidence-036", topicId: "confidence", text: "Talk about failure that didn’t define you." },
  { id: "confidence-037", topicId: "confidence", text: "What’s a story you tell about yourself that you’re rewriting?" },
  { id: "confidence-038", topicId: "confidence", text: "Describe feeling ready before you felt ready." },
  { id: "confidence-039", topicId: "confidence", text: "When does humor help your confidence?" },
  { id: "confidence-040", topicId: "confidence", text: "How do you stay confident around people who intimidate you?" },
  { id: "confidence-041", topicId: "confidence", text: "Talk about dressing, posture, or rituals that help you show up." },
  { id: "confidence-042", topicId: "confidence", text: "What’s something you stopped apologizing for?" },
  { id: "confidence-043", topicId: "confidence", text: "Describe leadership that felt natural." },
  { id: "confidence-044", topicId: "confidence", text: "When do you feel small—and what helps?" },
  { id: "confidence-045", topicId: "confidence", text: "How do friends influence your confidence?" },
  { id: "confidence-046", topicId: "confidence", text: "Talk about a win nobody else saw." },
  { id: "confidence-047", topicId: "confidence", text: "What’s the difference between arrogance and healthy pride for you?" },
  { id: "confidence-048", topicId: "confidence", text: "Describe recovering your voice after being interrupted or ignored." },
  { id: "confidence-049", topicId: "confidence", text: "When do you feel aligned—thoughts, words, and actions?" },
  { id: "confidence-050", topicId: "confidence", text: "What’s one confidence habit you want to keep?" },
  { id: "confidence-051", topicId: "confidence", text: "Talk about class presentations and what it brings up for you." },
  { id: "confidence-052", topicId: "confidence", text: "Describe a recent experience related to introducing yourself." },
  { id: "confidence-053", topicId: "confidence", text: "What have you noticed about yourself around job interviews?" },
  { id: "confidence-054", topicId: "confidence", text: "How does auditions show up in your life right now?" },
  { id: "confidence-055", topicId: "confidence", text: "Share a story connected to posting online." },
  { id: "confidence-056", topicId: "confidence", text: "Talk about staying offline and what it brings up for you." },
  { id: "confidence-057", topicId: "confidence", text: "Describe a recent experience related to eye contact." },
  { id: "confidence-058", topicId: "confidence", text: "What have you noticed about yourself around steady voice?" },
  { id: "confidence-059", topicId: "confidence", text: "How does posture show up in your life right now?" },
  { id: "confidence-060", topicId: "confidence", text: "Share a story connected to pauses." },
  { id: "confidence-061", topicId: "confidence", text: "Talk about filler words and what it brings up for you." },
  { id: "confidence-062", topicId: "confidence", text: "Describe a recent experience related to clear asks." },
  { id: "confidence-063", topicId: "confidence", text: "What have you noticed about yourself around saying no?" },
  { id: "confidence-064", topicId: "confidence", text: "How does saying yes show up in your life right now?" },
  { id: "confidence-065", topicId: "confidence", text: "Share a story connected to negotiating." },
  { id: "confidence-066", topicId: "confidence", text: "Talk about advocating and what it brings up for you." },
  { id: "confidence-067", topicId: "confidence", text: "Describe a recent experience related to leader roles." },
  { id: "confidence-068", topicId: "confidence", text: "What have you noticed about yourself around follower roles?" },
  { id: "confidence-069", topicId: "confidence", text: "How does expert moments show up in your life right now?" },
  { id: "confidence-070", topicId: "confidence", text: "Share a story connected to beginner moments." },
  { id: "confidence-071", topicId: "confidence", text: "Talk about praise and what it brings up for you." },
  { id: "confidence-072", topicId: "confidence", text: "Describe a recent experience related to critique." },
  { id: "confidence-073", topicId: "confidence", text: "What have you noticed about yourself around silence from others?" },
  { id: "confidence-074", topicId: "confidence", text: "How does applause show up in your life right now?" },
  { id: "confidence-075", topicId: "confidence", text: "Share a story connected to mirror pep talks." },
  { id: "confidence-076", topicId: "confidence", text: "Talk about friend pep talks and what it brings up for you." },
  { id: "confidence-077", topicId: "confidence", text: "Describe a recent experience related to journaling wins." },
  { id: "confidence-078", topicId: "confidence", text: "What have you noticed about yourself around tracking progress?" },
  { id: "confidence-079", topicId: "confidence", text: "How does fashion confidence show up in your life right now?" },
  { id: "confidence-080", topicId: "confidence", text: "Share a story connected to skill confidence." },
  { id: "confidence-081", topicId: "confidence", text: "Talk about social confidence and what it brings up for you." },
  { id: "confidence-082", topicId: "confidence", text: "Describe a recent experience related to creative confidence." },
  { id: "confidence-083", topicId: "confidence", text: "What have you noticed about yourself around sports confidence?" },
  { id: "confidence-084", topicId: "confidence", text: "How does academic confidence show up in your life right now?" },
  { id: "confidence-085", topicId: "confidence", text: "Share a story connected to dating confidence." },
  { id: "confidence-086", topicId: "confidence", text: "Talk about friend confidence and what it brings up for you." },
  { id: "confidence-087", topicId: "confidence", text: "Describe a recent experience related to recovery days." },
  { id: "confidence-088", topicId: "confidence", text: "What have you noticed about yourself around high days?" },
  { id: "confidence-089", topicId: "confidence", text: "How does neutral days show up in your life right now?" },
  { id: "confidence-090", topicId: "confidence", text: "Share a story connected to comeback arcs." },
  { id: "confidence-091", topicId: "confidence", text: "Talk about comparison traps and what it brings up for you." },
  { id: "confidence-092", topicId: "confidence", text: "Describe a recent experience related to inspiration instead." },
  { id: "confidence-093", topicId: "confidence", text: "What have you noticed about yourself around role models?" },
  { id: "confidence-094", topicId: "confidence", text: "How does anti-role-models show up in your life right now?" },
  { id: "confidence-095", topicId: "confidence", text: "Share a story connected to perfectionism." },
  { id: "confidence-096", topicId: "confidence", text: "Talk about good enough and what it brings up for you." },
  { id: "confidence-097", topicId: "confidence", text: "Describe a recent experience related to done over perfect." },
  { id: "confidence-098", topicId: "confidence", text: "What have you noticed about yourself around shipping the thing?" },
  { id: "confidence-099", topicId: "confidence", text: "How does being seen show up in your life right now?" },
  { id: "confidence-100", topicId: "confidence", text: "Share a story connected to being heard." },
  { id: "confidence-101", topicId: "confidence", text: "Talk about being respected and what it brings up for you." },
  { id: "confidence-102", topicId: "confidence", text: "Describe a recent experience related to self-respect." },
];
