import type { BankQuestion } from "@/lib/questions/types";

export const CREATIVITY_QUESTIONS: BankQuestion[] = [
  { id: "creativity-001", topicId: "creativity", text: "What are you creating—or wishing you could create—right now?" },
  { id: "creativity-002", topicId: "creativity", text: "Talk about where your ideas usually come from." },
  { id: "creativity-003", topicId: "creativity", text: "Describe a time you made something just because it felt good." },
  { id: "creativity-004", topicId: "creativity", text: "When do you feel most expressive?" },
  { id: "creativity-005", topicId: "creativity", text: "How do you handle creative blocks?" },
  { id: "creativity-006", topicId: "creativity", text: "Talk about sharing your work before it felt finished." },
  { id: "creativity-007", topicId: "creativity", text: "What’s an experiment that taught you something?" },
  { id: "creativity-008", topicId: "creativity", text: "Describe inspiration that hit at a random moment." },
  { id: "creativity-009", topicId: "creativity", text: "When does perfectionism stop you from starting?" },
  { id: "creativity-010", topicId: "creativity", text: "How do you know a piece or idea is “done enough”?" },
  { id: "creativity-011", topicId: "creativity", text: "Talk about collaborating creatively with someone." },
  { id: "creativity-012", topicId: "creativity", text: "What’s messy about your creative process that still works?" },
  { id: "creativity-013", topicId: "creativity", text: "Describe a style or voice you’re developing." },
  { id: "creativity-014", topicId: "creativity", text: "When do you create for an audience versus for yourself?" },
  { id: "creativity-015", topicId: "creativity", text: "How does feedback help—or hurt—your making?" },
  { id: "creativity-016", topicId: "creativity", text: "Talk about a tool, medium, or app that unlocked something." },
  { id: "creativity-017", topicId: "creativity", text: "What’s a creative risk you want to take?" },
  { id: "creativity-018", topicId: "creativity", text: "Describe remixing influences without copying." },
  { id: "creativity-019", topicId: "creativity", text: "When does play lead to better ideas than pressure?" },
  { id: "creativity-020", topicId: "creativity", text: "How do you capture ideas before they disappear?" },
  { id: "creativity-021", topicId: "creativity", text: "Talk about unfinished projects and how you feel about them." },
  { id: "creativity-022", topicId: "creativity", text: "What’s changing in what you want to make?" },
  { id: "creativity-023", topicId: "creativity", text: "Describe a creative community that nourishes you." },
  { id: "creativity-024", topicId: "creativity", text: "When do you feel envy of other creators—and what do you do with it?" },
  { id: "creativity-025", topicId: "creativity", text: "How do constraints make you more inventive?" },
  { id: "creativity-026", topicId: "creativity", text: "Talk about boredom as a doorway to ideas." },
  { id: "creativity-027", topicId: "creativity", text: "What’s something weird you love that fuels your creativity?" },
  { id: "creativity-028", topicId: "creativity", text: "Describe presenting or performing creative work." },
  { id: "creativity-029", topicId: "creativity", text: "When is rest part of the creative cycle?" },
  { id: "creativity-030", topicId: "creativity", text: "How do you protect creative time?" },
  { id: "creativity-031", topicId: "creativity", text: "Talk about failure in making—and trying again." },
  { id: "creativity-032", topicId: "creativity", text: "What’s a childhood creative habit you still have?" },
  { id: "creativity-033", topicId: "creativity", text: "Describe color, sound, texture, or rhythm that inspires you." },
  { id: "creativity-034", topicId: "creativity", text: "When do you edit harshly—and when do you stay gentle?" },
  { id: "creativity-035", topicId: "creativity", text: "How do you turn feelings into something made?" },
  { id: "creativity-036", topicId: "creativity", text: "Talk about originality—what does it mean to you?" },
  { id: "creativity-037", topicId: "creativity", text: "What’s hard about being seen as “the creative one”?" },
  { id: "creativity-038", topicId: "creativity", text: "Describe a breakthrough after a long stuck period." },
  { id: "creativity-039", topicId: "creativity", text: "When do deadlines help your creativity?" },
  { id: "creativity-040", topicId: "creativity", text: "How do you learn new creative skills?" },
  { id: "creativity-041", topicId: "creativity", text: "Talk about taste—how yours is evolving." },
  { id: "creativity-042", topicId: "creativity", text: "What’s a project you’d make if nobody would judge it?" },
  { id: "creativity-043", topicId: "creativity", text: "Describe teaching someone a creative technique." },
  { id: "creativity-044", topicId: "creativity", text: "When does comparison kill the joy of making?" },
  { id: "creativity-045", topicId: "creativity", text: "How do you celebrate finishing something?" },
  { id: "creativity-046", topicId: "creativity", text: "Talk about cross-pollinating hobbies into art." },
  { id: "creativity-047", topicId: "creativity", text: "What’s sacred about your creative space or playlist?" },
  { id: "creativity-048", topicId: "creativity", text: "Describe improvising when a plan fell apart." },
  { id: "creativity-049", topicId: "creativity", text: "When do you feel brave in what you make?" },
  { id: "creativity-050", topicId: "creativity", text: "What’s one creative habit you want to keep for life?" },
  { id: "creativity-051", topicId: "creativity", text: "Talk about sketchbooks and what it brings up for you." },
  { id: "creativity-052", topicId: "creativity", text: "Describe a recent experience related to drafts." },
  { id: "creativity-053", topicId: "creativity", text: "What have you noticed about yourself around demos?" },
  { id: "creativity-054", topicId: "creativity", text: "How does prototypes show up in your life right now?" },
  { id: "creativity-055", topicId: "creativity", text: "Share a story connected to paint." },
  { id: "creativity-056", topicId: "creativity", text: "Talk about pixels and what it brings up for you." },
  { id: "creativity-057", topicId: "creativity", text: "Describe a recent experience related to prose." },
  { id: "creativity-058", topicId: "creativity", text: "What have you noticed about yourself around poetry?" },
  { id: "creativity-059", topicId: "creativity", text: "How does songs show up in your life right now?" },
  { id: "creativity-060", topicId: "creativity", text: "Share a story connected to beats." },
  { id: "creativity-061", topicId: "creativity", text: "Talk about films and what it brings up for you." },
  { id: "creativity-062", topicId: "creativity", text: "Describe a recent experience related to photos." },
  { id: "creativity-063", topicId: "creativity", text: "What have you noticed about yourself around dance?" },
  { id: "creativity-064", topicId: "creativity", text: "How does design show up in your life right now?" },
  { id: "creativity-065", topicId: "creativity", text: "Share a story connected to fashion." },
  { id: "creativity-066", topicId: "creativity", text: "Talk about crafts and what it brings up for you." },
  { id: "creativity-067", topicId: "creativity", text: "Describe a recent experience related to stage." },
  { id: "creativity-068", topicId: "creativity", text: "What have you noticed about yourself around studio?" },
  { id: "creativity-069", topicId: "creativity", text: "How does bedroom desk show up in your life right now?" },
  { id: "creativity-070", topicId: "creativity", text: "Share a story connected to outdoors." },
  { id: "creativity-071", topicId: "creativity", text: "Talk about brainstorms and what it brings up for you." },
  { id: "creativity-072", topicId: "creativity", text: "Describe a recent experience related to mind maps." },
  { id: "creativity-073", topicId: "creativity", text: "What have you noticed about yourself around mood boards?" },
  { id: "creativity-074", topicId: "creativity", text: "How does scrap notes show up in your life right now?" },
  { id: "creativity-075", topicId: "creativity", text: "Share a story connected to critiques." },
  { id: "creativity-076", topicId: "creativity", text: "Talk about workshops and what it brings up for you." },
  { id: "creativity-077", topicId: "creativity", text: "Describe a recent experience related to open mics." },
  { id: "creativity-078", topicId: "creativity", text: "What have you noticed about yourself around galleries?" },
  { id: "creativity-079", topicId: "creativity", text: "How does Instagram shares show up in your life right now?" },
  { id: "creativity-080", topicId: "creativity", text: "Share a story connected to private folders." },
  { id: "creativity-081", topicId: "creativity", text: "Talk about collabs and what it brings up for you." },
  { id: "creativity-082", topicId: "creativity", text: "Describe a recent experience related to solos." },
  { id: "creativity-083", topicId: "creativity", text: "What have you noticed about yourself around writer’s block?" },
  { id: "creativity-084", topicId: "creativity", text: "How does blank page fear show up in your life right now?" },
  { id: "creativity-085", topicId: "creativity", text: "Share a story connected to too many ideas." },
  { id: "creativity-086", topicId: "creativity", text: "Talk about one clear idea and what it brings up for you." },
  { id: "creativity-087", topicId: "creativity", text: "Describe a recent experience related to deadlines." },
  { id: "creativity-088", topicId: "creativity", text: "What have you noticed about yourself around open-ended time?" },
  { id: "creativity-089", topicId: "creativity", text: "How does commissions show up in your life right now?" },
  { id: "creativity-090", topicId: "creativity", text: "Share a story connected to personal projects." },
  { id: "creativity-091", topicId: "creativity", text: "Talk about fan art energy and what it brings up for you." },
  { id: "creativity-092", topicId: "creativity", text: "Describe a recent experience related to original worlds." },
  { id: "creativity-093", topicId: "creativity", text: "What have you noticed about yourself around memoir vibes?" },
  { id: "creativity-094", topicId: "creativity", text: "How does fiction show up in your life right now?" },
  { id: "creativity-095", topicId: "creativity", text: "Share a story connected to tools upgrading." },
  { id: "creativity-096", topicId: "creativity", text: "Talk about limitations and what it brings up for you." },
  { id: "creativity-097", topicId: "creativity", text: "Describe a recent experience related to found materials." },
  { id: "creativity-098", topicId: "creativity", text: "What have you noticed about yourself around digital tools?" },
  { id: "creativity-099", topicId: "creativity", text: "How does morning makes show up in your life right now?" },
  { id: "creativity-100", topicId: "creativity", text: "Share a story connected to night makes." },
  { id: "creativity-101", topicId: "creativity", text: "Talk about weekend sprints and what it brings up for you." },
  { id: "creativity-102", topicId: "creativity", text: "Describe a recent experience related to slow seasons." },
  { id: "creativity-103", topicId: "creativity", text: "What have you noticed about yourself around museums?" },
  { id: "creativity-104", topicId: "creativity", text: "How does nature walks show up in your life right now?" },
  { id: "creativity-105", topicId: "creativity", text: "Share a story connected to conversations." },
  { id: "creativity-106", topicId: "creativity", text: "Talk about dreams and what it brings up for you." },
];
