import type { BankQuestion } from "@/lib/questions/types";

export const EMOTIONS_QUESTIONS: BankQuestion[] = [
  { id: "emotions-001", topicId: "emotions", text: "What emotion have you been carrying that you haven’t said out loud?" },
  { id: "emotions-002", topicId: "emotions", text: "Talk about a moment of joy from recently." },
  { id: "emotions-003", topicId: "emotions", text: "How do you notice sadness in your body?" },
  { id: "emotions-004", topicId: "emotions", text: "Describe anger that felt justified—and what you did with it." },
  { id: "emotions-005", topicId: "emotions", text: "When do you feel calmest?" },
  { id: "emotions-006", topicId: "emotions", text: "Talk about anxiety showing up before something important." },
  { id: "emotions-007", topicId: "emotions", text: "What does tenderness mean in how you treat yourself?" },
  { id: "emotions-008", topicId: "emotions", text: "Describe a time you felt overwhelmed and found a way through." },
  { id: "emotions-009", topicId: "emotions", text: "How do you name feelings when words are hard?" },
  { id: "emotions-010", topicId: "emotions", text: "Talk about numbness—when feelings go quiet." },
  { id: "emotions-011", topicId: "emotions", text: "What’s an emotion you used to hide?" },
  { id: "emotions-012", topicId: "emotions", text: "Describe laughing until you cried—or crying then laughing." },
  { id: "emotions-013", topicId: "emotions", text: "When do emotions feel too big for the room you’re in?" },
  { id: "emotions-014", topicId: "emotions", text: "How do you comfort yourself without making things worse?" },
  { id: "emotions-015", topicId: "emotions", text: "Talk about envy and what it pointed you toward." },
  { id: "emotions-016", topicId: "emotions", text: "Describe gratitude that surprised you." },
  { id: "emotions-017", topicId: "emotions", text: "What’s the difference between loneliness and being alone for you?" },
  { id: "emotions-018", topicId: "emotions", text: "Talk about excitement that made you restless." },
  { id: "emotions-019", topicId: "emotions", text: "When do you feel proud in a quiet way?" },
  { id: "emotions-020", topicId: "emotions", text: "How do other people’s moods affect yours?" },
  { id: "emotions-021", topicId: "emotions", text: "Describe a feeling you misunderstood at first." },
  { id: "emotions-022", topicId: "emotions", text: "What’s hard about being vulnerable with emotion?" },
  { id: "emotions-023", topicId: "emotions", text: "Talk about shame—and softening it." },
  { id: "emotions-024", topicId: "emotions", text: "Describe relief after something finally ended or began." },
  { id: "emotions-025", topicId: "emotions", text: "When does hope feel risky?" },
  { id: "emotions-026", topicId: "emotions", text: "How do you express feelings without dumping them on people?" },
  { id: "emotions-027", topicId: "emotions", text: "Talk about boredom and what it’s asking for." },
  { id: "emotions-028", topicId: "emotions", text: "Describe a soundtrack or place that matches a feeling." },
  { id: "emotions-029", topicId: "emotions", text: "What’s changing about how you handle hard days?" },
  { id: "emotions-030", topicId: "emotions", text: "Talk about compassion for someone else’s emotion." },
  { id: "emotions-031", topicId: "emotions", text: "When do you intellectualize feelings instead of feeling them?" },
  { id: "emotions-032", topicId: "emotions", text: "Describe a cry that helped." },
  { id: "emotions-033", topicId: "emotions", text: "How do you know you’re avoiding something emotionally?" },
  { id: "emotions-034", topicId: "emotions", text: "Talk about feeling two opposite things at once." },
  { id: "emotions-035", topicId: "emotions", text: "What’s a gentle way you’ve learned to check in with yourself?" },
  { id: "emotions-036", topicId: "emotions", text: "Describe fear that protected you—and fear that limited you." },
  { id: "emotions-037", topicId: "emotions", text: "When do you feel most emotionally honest?" },
  { id: "emotions-038", topicId: "emotions", text: "How do sleep, food, or movement change your mood?" },
  { id: "emotions-039", topicId: "emotions", text: "Talk about a trigger you recognize now." },
  { id: "emotions-040", topicId: "emotions", text: "Describe celebrating a feeling instead of rushing past it." },
  { id: "emotions-041", topicId: "emotions", text: "What’s something you need when you’re low?" },
  { id: "emotions-042", topicId: "emotions", text: "Talk about emotional labor you carry." },
  { id: "emotions-043", topicId: "emotions", text: "When is silence the kindest response?" },
  { id: "emotions-044", topicId: "emotions", text: "Describe reclaiming a feeling you were told not to have." },
  { id: "emotions-045", topicId: "emotions", text: "How do you repair after snapping at someone?" },
  { id: "emotions-046", topicId: "emotions", text: "Talk about awe or wonder you’ve felt lately." },
  { id: "emotions-047", topicId: "emotions", text: "What’s heavy that you’re ready to set down a little?" },
  { id: "emotions-048", topicId: "emotions", text: "Describe emotional growth you can see looking back." },
  { id: "emotions-049", topicId: "emotions", text: "When do you feel safe enough to feel fully?" },
  { id: "emotions-050", topicId: "emotions", text: "What’s one emotion you want a better relationship with?" },
  { id: "emotions-051", topicId: "emotions", text: "Talk about morning moods and what it brings up for you." },
  { id: "emotions-052", topicId: "emotions", text: "Describe a recent experience related to late-night feelings." },
  { id: "emotions-053", topicId: "emotions", text: "What have you noticed about yourself around after school crash?" },
  { id: "emotions-054", topicId: "emotions", text: "How does weekend ease show up in your life right now?" },
  { id: "emotions-055", topicId: "emotions", text: "Share a story connected to social anxiety." },
  { id: "emotions-056", topicId: "emotions", text: "Talk about performance nerves and what it brings up for you." },
  { id: "emotions-057", topicId: "emotions", text: "Describe a recent experience related to home stress." },
  { id: "emotions-058", topicId: "emotions", text: "What have you noticed about yourself around friend stress?" },
  { id: "emotions-059", topicId: "emotions", text: "How does heartbreak show up in your life right now?" },
  { id: "emotions-060", topicId: "emotions", text: "Share a story connected to homesickness." },
  { id: "emotions-061", topicId: "emotions", text: "Talk about nostalgia and what it brings up for you." },
  { id: "emotions-062", topicId: "emotions", text: "Describe a recent experience related to anticipation." },
  { id: "emotions-063", topicId: "emotions", text: "What have you noticed about yourself around irritation?" },
  { id: "emotions-064", topicId: "emotions", text: "How does rage show up in your life right now?" },
  { id: "emotions-065", topicId: "emotions", text: "Share a story connected to irritable hunger." },
  { id: "emotions-066", topicId: "emotions", text: "Talk about tired tears and what it brings up for you." },
  { id: "emotions-067", topicId: "emotions", text: "Describe a recent experience related to giddy joy." },
  { id: "emotions-068", topicId: "emotions", text: "What have you noticed about yourself around quiet contentment?" },
  { id: "emotions-069", topicId: "emotions", text: "How does bittersweet show up in your life right now?" },
  { id: "emotions-070", topicId: "emotions", text: "Share a story connected to mixed feelings." },
  { id: "emotions-071", topicId: "emotions", text: "Talk about panic and what it brings up for you." },
  { id: "emotions-072", topicId: "emotions", text: "Describe a recent experience related to worry loops." },
  { id: "emotions-073", topicId: "emotions", text: "What have you noticed about yourself around racing thoughts?" },
  { id: "emotions-074", topicId: "emotions", text: "How does slow sadness show up in your life right now?" },
  { id: "emotions-075", topicId: "emotions", text: "Share a story connected to body tension." },
  { id: "emotions-076", topicId: "emotions", text: "Talk about shallow breath and what it brings up for you." },
  { id: "emotions-077", topicId: "emotions", text: "Describe a recent experience related to heavy chest." },
  { id: "emotions-078", topicId: "emotions", text: "What have you noticed about yourself around lightness?" },
  { id: "emotions-079", topicId: "emotions", text: "How does journaling feelings show up in your life right now?" },
  { id: "emotions-080", topicId: "emotions", text: "Share a story connected to talking it out." },
  { id: "emotions-081", topicId: "emotions", text: "Talk about walking it off and what it brings up for you." },
  { id: "emotions-082", topicId: "emotions", text: "Describe a recent experience related to music as medicine." },
  { id: "emotions-083", topicId: "emotions", text: "What have you noticed about yourself around crying in private?" },
  { id: "emotions-084", topicId: "emotions", text: "How does crying with someone show up in your life right now?" },
  { id: "emotions-085", topicId: "emotions", text: "Share a story connected to not crying." },
  { id: "emotions-086", topicId: "emotions", text: "Talk about tears of relief and what it brings up for you." },
  { id: "emotions-087", topicId: "emotions", text: "Describe a recent experience related to feeling dismissed." },
  { id: "emotions-088", topicId: "emotions", text: "What have you noticed about yourself around feeling validated?" },
  { id: "emotions-089", topicId: "emotions", text: "How does feeling too much show up in your life right now?" },
  { id: "emotions-090", topicId: "emotions", text: "Share a story connected to feeling too little." },
  { id: "emotions-091", topicId: "emotions", text: "Talk about empathy overload and what it brings up for you." },
  { id: "emotions-092", topicId: "emotions", text: "Describe a recent experience related to compassion fatigue." },
  { id: "emotions-093", topicId: "emotions", text: "What have you noticed about yourself around boundaries?" },
  { id: "emotions-094", topicId: "emotions", text: "How does openness show up in your life right now?" },
  { id: "emotions-095", topicId: "emotions", text: "Share a story connected to mood swings." },
  { id: "emotions-096", topicId: "emotions", text: "Talk about steady days and what it brings up for you." },
  { id: "emotions-097", topicId: "emotions", text: "Describe a recent experience related to breakthroughs." },
  { id: "emotions-098", topicId: "emotions", text: "What have you noticed about yourself around setbacks?" },
  { id: "emotions-099", topicId: "emotions", text: "How does self-talk show up in your life right now?" },
  { id: "emotions-100", topicId: "emotions", text: "Share a story connected to inner critic." },
  { id: "emotions-101", topicId: "emotions", text: "Talk about inner friend and what it brings up for you." },
  { id: "emotions-102", topicId: "emotions", text: "Describe a recent experience related to permission to feel." },
];
