import type { BankQuestion } from "@/lib/questions/types";

export const FAMILY_QUESTIONS: BankQuestion[] = [
  { id: "family-001", topicId: "family", text: "Describe a typical evening at home." },
  { id: "family-002", topicId: "family", text: "Who in your family do you talk to most easily?" },
  { id: "family-003", topicId: "family", text: "What tradition matters to your family?" },
  { id: "family-004", topicId: "family", text: "Talk about a time family supported you." },
  { id: "family-005", topicId: "family", text: "What expectations do you feel at home?" },
  { id: "family-006", topicId: "family", text: "Describe a meal that feels like home." },
  { id: "family-007", topicId: "family", text: "When is it hard to speak up with family?" },
  { id: "family-008", topicId: "family", text: "What do you wish your family understood better?" },
  { id: "family-009", topicId: "family", text: "Talk about a family member you admire." },
  { id: "family-010", topicId: "family", text: "How has your role in the family changed?" },
  { id: "family-011", topicId: "family", text: "Describe a disagreement at home that stayed respectful." },
  { id: "family-012", topicId: "family", text: "What makes you feel safe at home?" },
  { id: "family-013", topicId: "family", text: "Talk about helping out around the house." },
  { id: "family-014", topicId: "family", text: "When do you need space from family?" },
  { id: "family-015", topicId: "family", text: "What’s something funny that happens in your family?" },
  { id: "family-016", topicId: "family", text: "Describe teaching something to a family member." },
  { id: "family-017", topicId: "family", text: "How do you show care at home?" },
  { id: "family-018", topicId: "family", text: "Talk about a holiday or celebration that stands out." },
  { id: "family-019", topicId: "family", text: "What boundaries are you learning with family?" },
  { id: "family-020", topicId: "family", text: "Describe feeling proud of someone in your family." },
  { id: "family-021", topicId: "family", text: "When do family conversations get tense?" },
  { id: "family-022", topicId: "family", text: "What’s a story your family tells about you?" },
  { id: "family-023", topicId: "family", text: "Talk about independence versus closeness at home." },
  { id: "family-024", topicId: "family", text: "How do you handle advice you didn’t ask for?" },
  { id: "family-025", topicId: "family", text: "Describe a quiet moment with family that meant something." },
  { id: "family-026", topicId: "family", text: "What does respect look like in your household?" },
  { id: "family-027", topicId: "family", text: "Talk about missing someone in your family." },
  { id: "family-028", topicId: "family", text: "When do you feel most yourself at home?" },
  { id: "family-029", topicId: "family", text: "What’s changing in your family right now?" },
  { id: "family-030", topicId: "family", text: "Describe sharing good news at home." },
  { id: "family-031", topicId: "family", text: "How do siblings or close relatives shape you?" },
  { id: "family-032", topicId: "family", text: "Talk about a chore or responsibility you take seriously." },
  { id: "family-033", topicId: "family", text: "What do you appreciate that you used to overlook?" },
  { id: "family-034", topicId: "family", text: "Describe a time you felt misunderstood at home." },
  { id: "family-035", topicId: "family", text: "How do you reconnect after a hard day with family?" },
  { id: "family-036", topicId: "family", text: "What’s a value your family taught you?" },
  { id: "family-037", topicId: "family", text: "Talk about privacy and sharing at home." },
  { id: "family-038", topicId: "family", text: "When do you ask family for help?" },
  { id: "family-039", topicId: "family", text: "Describe a road trip or outing with family." },
  { id: "family-040", topicId: "family", text: "What makes home feel chaotic—and how do you cope?" },
  { id: "family-041", topicId: "family", text: "Talk about a compliment from a parent or guardian that stuck." },
  { id: "family-042", topicId: "family", text: "How do you talk about school or work at home?" },
  { id: "family-043", topicId: "family", text: "Describe inventing a new small tradition." },
  { id: "family-044", topicId: "family", text: "What do you protect about your family when talking to others?" },
  { id: "family-045", topicId: "family", text: "Talk about forgiveness in your family." },
  { id: "family-046", topicId: "family", text: "When do you feel pressure to be a certain way?" },
  { id: "family-047", topicId: "family", text: "What’s something you’re grateful for at home?" },
  { id: "family-048", topicId: "family", text: "Describe listening to a family member’s hard day." },
  { id: "family-049", topicId: "family", text: "How has trust grown or shifted at home?" },
  { id: "family-050", topicId: "family", text: "What would you change about communication at home if you could?" },
  { id: "family-051", topicId: "family", text: "Talk about morning routines and what it brings up for you." },
  { id: "family-052", topicId: "family", text: "Describe a recent experience related to weekend mornings." },
  { id: "family-053", topicId: "family", text: "What have you noticed about yourself around shared humor?" },
  { id: "family-054", topicId: "family", text: "How does quiet evenings show up in your life right now?" },
  { id: "family-055", topicId: "family", text: "Share a story connected to loud dinners." },
  { id: "family-056", topicId: "family", text: "Talk about chores and what it brings up for you." },
  { id: "family-057", topicId: "family", text: "Describe a recent experience related to rules." },
  { id: "family-058", topicId: "family", text: "What have you noticed about yourself around freedom?" },
  { id: "family-059", topicId: "family", text: "How does checking in show up in your life right now?" },
  { id: "family-060", topicId: "family", text: "Share a story connected to checking out." },
  { id: "family-061", topicId: "family", text: "Talk about grandparents and what it brings up for you." },
  { id: "family-062", topicId: "family", text: "Describe a recent experience related to cousins." },
  { id: "family-063", topicId: "family", text: "What have you noticed about yourself around parents?" },
  { id: "family-064", topicId: "family", text: "How does guardians show up in your life right now?" },
  { id: "family-065", topicId: "family", text: "Share a story connected to siblings." },
  { id: "family-066", topicId: "family", text: "Talk about only-child moments and what it brings up for you." },
  { id: "family-067", topicId: "family", text: "Describe a recent experience related to family photos." },
  { id: "family-068", topicId: "family", text: "What have you noticed about yourself around old stories?" },
  { id: "family-069", topicId: "family", text: "How does new changes show up in your life right now?" },
  { id: "family-070", topicId: "family", text: "Share a story connected to moving." },
  { id: "family-071", topicId: "family", text: "Talk about staying put and what it brings up for you." },
  { id: "family-072", topicId: "family", text: "Describe a recent experience related to cultural traditions." },
  { id: "family-073", topicId: "family", text: "What have you noticed about yourself around faith or values?" },
  { id: "family-074", topicId: "family", text: "How does food you love show up in your life right now?" },
  { id: "family-075", topicId: "family", text: "Share a story connected to food you avoid." },
  { id: "family-076", topicId: "family", text: "Talk about feeling young and what it brings up for you." },
  { id: "family-077", topicId: "family", text: "Describe a recent experience related to feeling grown." },
  { id: "family-078", topicId: "family", text: "What have you noticed about yourself around asking permission?" },
  { id: "family-079", topicId: "family", text: "How does making your own choices show up in your life right now?" },
  { id: "family-080", topicId: "family", text: "Share a story connected to money conversations." },
  { id: "family-081", topicId: "family", text: "Talk about future plans and what it brings up for you." },
  { id: "family-082", topicId: "family", text: "Describe a recent experience related to past mistakes." },
  { id: "family-083", topicId: "family", text: "What have you noticed about yourself around second chances?" },
  { id: "family-084", topicId: "family", text: "How does apologies show up in your life right now?" },
  { id: "family-085", topicId: "family", text: "Share a story connected to pride." },
  { id: "family-086", topicId: "family", text: "Talk about worry and what it brings up for you." },
  { id: "family-087", topicId: "family", text: "Describe a recent experience related to protection." },
  { id: "family-088", topicId: "family", text: "What have you noticed about yourself around independence?" },
  { id: "family-089", topicId: "family", text: "How does belonging show up in your life right now?" },
  { id: "family-090", topicId: "family", text: "Share a story connected to being compared." },
  { id: "family-091", topicId: "family", text: "Talk about being trusted and what it brings up for you." },
  { id: "family-092", topicId: "family", text: "Describe a recent experience related to being babysat." },
  { id: "family-093", topicId: "family", text: "What have you noticed about yourself around babysitting?" },
  { id: "family-094", topicId: "family", text: "How does family friends show up in your life right now?" },
  { id: "family-095", topicId: "family", text: "Share a story connected to house guests." },
  { id: "family-096", topicId: "family", text: "Talk about alone time and what it brings up for you." },
  { id: "family-097", topicId: "family", text: "Describe a recent experience related to together time." },
  { id: "family-098", topicId: "family", text: "What have you noticed about yourself around texting family?" },
  { id: "family-099", topicId: "family", text: "How does calling family show up in your life right now?" },
  { id: "family-100", topicId: "family", text: "Share a story connected to surprising them." },
  { id: "family-101", topicId: "family", text: "Talk about being surprised and what it brings up for you." },
];
