import type { BankQuestion } from "@/lib/questions/types";

export const FRIENDSHIPS_QUESTIONS: BankQuestion[] = [
  { id: "friendships-001", topicId: "friendships", text: "Who in your friend group do you feel most yourself with, and why?" },
  { id: "friendships-002", topicId: "friendships", text: "Describe a friendship that changed you." },
  { id: "friendships-003", topicId: "friendships", text: "What does loyalty look like in your friendships?" },
  { id: "friendships-004", topicId: "friendships", text: "Talk about a time a friend surprised you." },
  { id: "friendships-005", topicId: "friendships", text: "What makes hanging out with friends feel easy?" },
  { id: "friendships-006", topicId: "friendships", text: "When do friendships feel hard for you?" },
  { id: "friendships-007", topicId: "friendships", text: "Describe a moment you felt left out." },
  { id: "friendships-008", topicId: "friendships", text: "What do you wish friends understood about you?" },
  { id: "friendships-009", topicId: "friendships", text: "Talk about a friendship you’re proud of keeping." },
  { id: "friendships-010", topicId: "friendships", text: "How do you show someone you care without saying it?" },
  { id: "friendships-011", topicId: "friendships", text: "What’s a small habit you and a friend share?" },
  { id: "friendships-012", topicId: "friendships", text: "Describe the last time you laughed hard with friends." },
  { id: "friendships-013", topicId: "friendships", text: "What kind of friend are you at your best?" },
  { id: "friendships-014", topicId: "friendships", text: "Talk about a disagreement with a friend that taught you something." },
  { id: "friendships-015", topicId: "friendships", text: "Who do you go to when something is weighing on you?" },
  { id: "friendships-016", topicId: "friendships", text: "What does “being there” for someone mean to you?" },
  { id: "friendships-017", topicId: "friendships", text: "Describe a time you felt truly included." },
  { id: "friendships-018", topicId: "friendships", text: "What’s something you’ve never told a friend but maybe should?" },
  { id: "friendships-019", topicId: "friendships", text: "How do group chats make you feel?" },
  { id: "friendships-020", topicId: "friendships", text: "Talk about a friend who brings out a different side of you." },
  { id: "friendships-021", topicId: "friendships", text: "What boundaries matter most in friendships?" },
  { id: "friendships-022", topicId: "friendships", text: "Describe meeting someone new and clicking right away." },
  { id: "friendships-023", topicId: "friendships", text: "When do you prefer one-on-one over a group?" },
  { id: "friendships-024", topicId: "friendships", text: "What’s a friendship you’ve outgrown, and how did that feel?" },
  { id: "friendships-025", topicId: "friendships", text: "Talk about supporting a friend through something hard." },
  { id: "friendships-026", topicId: "friendships", text: "What compliments from friends stick with you?" },
  { id: "friendships-027", topicId: "friendships", text: "How do you handle jealousy in friendships?" },
  { id: "friendships-028", topicId: "friendships", text: "Describe a spontaneous plan with friends that went well." },
  { id: "friendships-029", topicId: "friendships", text: "What does trust look like day to day?" },
  { id: "friendships-030", topicId: "friendships", text: "Talk about apologizing to a friend." },
  { id: "friendships-031", topicId: "friendships", text: "When is it hard to ask friends for help?" },
  { id: "friendships-032", topicId: "friendships", text: "What’s your favorite way to spend time with friends?" },
  { id: "friendships-033", topicId: "friendships", text: "Describe a friend who challenges you in a good way." },
  { id: "friendships-034", topicId: "friendships", text: "How do you reconnect after drifting apart?" },
  { id: "friendships-035", topicId: "friendships", text: "What inside jokes say about your friendships?" },
  { id: "friendships-036", topicId: "friendships", text: "Talk about feeling different from your friends." },
  { id: "friendships-037", topicId: "friendships", text: "When do you hold back around friends?" },
  { id: "friendships-038", topicId: "friendships", text: "What’s a risk you took for a friendship?" },
  { id: "friendships-039", topicId: "friendships", text: "Describe introducing friends from different parts of your life." },
  { id: "friendships-040", topicId: "friendships", text: "How do you celebrate friends’ wins?" },
  { id: "friendships-041", topicId: "friendships", text: "Talk about a time you misunderstood a friend." },
  { id: "friendships-042", topicId: "friendships", text: "What makes someone feel safe to open up to?" },
  { id: "friendships-043", topicId: "friendships", text: "Describe a quiet moment with a friend that meant a lot." },
  { id: "friendships-044", topicId: "friendships", text: "How has friendship changed for you this year?" },
  { id: "friendships-045", topicId: "friendships", text: "What’s something generous a friend did for you?" },
  { id: "friendships-046", topicId: "friendships", text: "Talk about peer pressure you’ve felt." },
  { id: "friendships-047", topicId: "friendships", text: "When do you feel most confident with friends?" },
  { id: "friendships-048", topicId: "friendships", text: "What’s a friendship goal you have?" },
  { id: "friendships-049", topicId: "friendships", text: "Describe texting vs talking in person with friends." },
  { id: "friendships-050", topicId: "friendships", text: "How do you know a friendship is healthy?" },
  { id: "friendships-051", topicId: "friendships", text: "Talk about a recent hangout and what it brings up for you." },
  { id: "friendships-052", topicId: "friendships", text: "Describe a recent experience related to someone you miss." },
  { id: "friendships-053", topicId: "friendships", text: "What have you noticed about yourself around a group dynamic?" },
  { id: "friendships-054", topicId: "friendships", text: "How does feeling popular show up in your life right now?" },
  { id: "friendships-055", topicId: "friendships", text: "Share a story connected to feeling invisible." },
  { id: "friendships-056", topicId: "friendships", text: "Talk about shared hobbies and what it brings up for you." },
  { id: "friendships-057", topicId: "friendships", text: "Describe a recent experience related to different opinions." },
  { id: "friendships-058", topicId: "friendships", text: "What have you noticed about yourself around making new friends?" },
  { id: "friendships-059", topicId: "friendships", text: "How does old friends show up in your life right now?" },
  { id: "friendships-060", topicId: "friendships", text: "Share a story connected to school friends." },
  { id: "friendships-061", topicId: "friendships", text: "Talk about online friends and what it brings up for you." },
  { id: "friendships-062", topicId: "friendships", text: "Describe a recent experience related to being honest." },
  { id: "friendships-063", topicId: "friendships", text: "What have you noticed about yourself around keeping secrets?" },
  { id: "friendships-064", topicId: "friendships", text: "How does plans falling through show up in your life right now?" },
  { id: "friendships-065", topicId: "friendships", text: "Share a story connected to being the organizer." },
  { id: "friendships-066", topicId: "friendships", text: "Talk about being invited last and what it brings up for you." },
  { id: "friendships-067", topicId: "friendships", text: "Describe a recent experience related to friendship effort." },
  { id: "friendships-068", topicId: "friendships", text: "What have you noticed about yourself around feeling drained?" },
  { id: "friendships-069", topicId: "friendships", text: "How does feeling energized show up in your life right now?" },
  { id: "friendships-070", topicId: "friendships", text: "Share a story connected to comparing yourself." },
  { id: "friendships-071", topicId: "friendships", text: "Talk about your role in the group and what it brings up for you." },
  { id: "friendships-072", topicId: "friendships", text: "Describe a recent experience related to someone quieter." },
  { id: "friendships-073", topicId: "friendships", text: "What have you noticed about yourself around someone louder?" },
  { id: "friendships-074", topicId: "friendships", text: "How does a funny memory show up in your life right now?" },
  { id: "friendships-075", topicId: "friendships", text: "Share a story connected to a serious talk." },
  { id: "friendships-076", topicId: "friendships", text: "Talk about a road trip vibe and what it brings up for you." },
  { id: "friendships-077", topicId: "friendships", text: "Describe a recent experience related to helping a friend study." },
  { id: "friendships-078", topicId: "friendships", text: "What have you noticed about yourself around celebrating together?" },
  { id: "friendships-079", topicId: "friendships", text: "How does disagreeing kindly show up in your life right now?" },
  { id: "friendships-080", topicId: "friendships", text: "Share a story connected to standing up for a friend." },
  { id: "friendships-081", topicId: "friendships", text: "Talk about feeling judged and what it brings up for you." },
  { id: "friendships-082", topicId: "friendships", text: "Describe a recent experience related to feeling accepted." },
  { id: "friendships-083", topicId: "friendships", text: "What have you noticed about yourself around changing friend groups?" },
  { id: "friendships-084", topicId: "friendships", text: "How does staying close long-distance show up in your life right now?" },
  { id: "friendships-085", topicId: "friendships", text: "Share a story connected to shared playlists." },
  { id: "friendships-086", topicId: "friendships", text: "Talk about shared meals and what it brings up for you." },
  { id: "friendships-087", topicId: "friendships", text: "Describe a recent experience related to late-night talks." },
  { id: "friendships-088", topicId: "friendships", text: "What have you noticed about yourself around awkward silences?" },
  { id: "friendships-089", topicId: "friendships", text: "How does first impressions show up in your life right now?" },
  { id: "friendships-090", topicId: "friendships", text: "Share a story connected to second chances." },
  { id: "friendships-091", topicId: "friendships", text: "Talk about loyalty tests and what it brings up for you." },
  { id: "friendships-092", topicId: "friendships", text: "Describe a recent experience related to small kindnesses." },
  { id: "friendships-093", topicId: "friendships", text: "What have you noticed about yourself around big favors?" },
  { id: "friendships-094", topicId: "friendships", text: "How does unspoken rules show up in your life right now?" },
  { id: "friendships-095", topicId: "friendships", text: "Share a story connected to group projects with friends." },
  { id: "friendships-096", topicId: "friendships", text: "Talk about weekend plans and what it brings up for you." },
  { id: "friendships-097", topicId: "friendships", text: "Describe a recent experience related to canceling plans." },
  { id: "friendships-098", topicId: "friendships", text: "What have you noticed about yourself around surprising someone?" },
  { id: "friendships-099", topicId: "friendships", text: "How does being surprised show up in your life right now?" },
  { id: "friendships-100", topicId: "friendships", text: "Share a story connected to growing apart gently." },
];
