import type { BankQuestion } from "@/lib/questions/types";

export const FUTURE_QUESTIONS: BankQuestion[] = [
  { id: "future-001", topicId: "future", text: "What future version of yourself are you curious about?" },
  { id: "future-002", topicId: "future", text: "Talk about a hope you’re carrying quietly." },
  { id: "future-003", topicId: "future", text: "When does uncertainty about the future feel heavy?" },
  { id: "future-004", topicId: "future", text: "Describe a plan you’re excited about—even if it’s fuzzy." },
  { id: "future-005", topicId: "future", text: "How do you talk about your future with others?" },
  { id: "future-006", topicId: "future", text: "What’s a fear tied to what’s next?" },
  { id: "future-007", topicId: "future", text: "Talk about ambition—what does wanting more look like for you?" },
  { id: "future-008", topicId: "future", text: "Describe a possibility that lights you up." },
  { id: "future-009", topicId: "future", text: "When do you feel behind compared to peers?" },
  { id: "future-010", topicId: "future", text: "What’s something you’re deliberately not rushing?" },
  { id: "future-011", topicId: "future", text: "Talk about a decision hanging over you." },
  { id: "future-012", topicId: "future", text: "Describe who you want to become in five years—without a perfect plan." },
  { id: "future-013", topicId: "future", text: "How do you handle advice about your future?" },
  { id: "future-014", topicId: "future", text: "What’s a skill you want future-you to thank you for starting?" },
  { id: "future-015", topicId: "future", text: "Talk about money, independence, or adulthood on the horizon." },
  { id: "future-016", topicId: "future", text: "Describe a path you almost took." },
  { id: "future-017", topicId: "future", text: "When does daydreaming help, and when does it distract?" },
  { id: "future-018", topicId: "future", text: "What’s changing about what success means to you?" },
  { id: "future-019", topicId: "future", text: "Talk about leaving something familiar someday." },
  { id: "future-020", topicId: "future", text: "Describe a city, school, job, or lifestyle you’re imagining." },
  { id: "future-021", topicId: "future", text: "How do relationships fit into your future picture?" },
  { id: "future-022", topicId: "future", text: "What’s a small step you can take this month?" },
  { id: "future-023", topicId: "future", text: "Talk about legacy—what do you want to leave behind, even small?" },
  { id: "future-024", topicId: "future", text: "Describe feeling ready versus feeling not ready." },
  { id: "future-025", topicId: "future", text: "When do timelines and deadlines stress you?" },
  { id: "future-026", topicId: "future", text: "What’s an unconventional option you’ve considered?" },
  { id: "future-027", topicId: "future", text: "Talk about role models for the life you want." },
  { id: "future-028", topicId: "future", text: "Describe rewriting a story you used to tell about your future." },
  { id: "future-029", topicId: "future", text: "How do you stay present while still planning?" },
  { id: "future-030", topicId: "future", text: "What’s unknown that you’re learning to sit with?" },
  { id: "future-031", topicId: "future", text: "Talk about backup plans—and how they make you feel." },
  { id: "future-032", topicId: "future", text: "Describe a risk that might be worth it." },
  { id: "future-033", topicId: "future", text: "When do you feel most optimistic?" },
  { id: "future-034", topicId: "future", text: "What’s a future conversation you’re rehearsing in your head?" },
  { id: "future-035", topicId: "future", text: "Talk about identity shifting as you grow." },
  { id: "future-036", topicId: "future", text: "Describe balancing practicality and imagination." },
  { id: "future-037", topicId: "future", text: "How do family expectations shape your future talk?" },
  { id: "future-038", topicId: "future", text: "What’s a dream you’d admit only here?" },
  { id: "future-039", topicId: "future", text: "Talk about failure as part of the path forward." },
  { id: "future-040", topicId: "future", text: "Describe a milestone you’re aiming for." },
  { id: "future-041", topicId: "future", text: "When does comparison steal your future joy?" },
  { id: "future-042", topicId: "future", text: "What’s something you’ll be glad you practiced saying?" },
  { id: "future-043", topicId: "future", text: "Talk about home—where might you belong later?" },
  { id: "future-044", topicId: "future", text: "Describe contributing something meaningful someday." },
  { id: "future-045", topicId: "future", text: "How do you want to treat people in your future life?" },
  { id: "future-046", topicId: "future", text: "What’s a habit future-you needs you to start?" },
  { id: "future-047", topicId: "future", text: "Talk about change you’re already sensing." },
  { id: "future-048", topicId: "future", text: "Describe courage in a small future-facing choice." },
  { id: "future-049", topicId: "future", text: "When do you feel the future is open?" },
  { id: "future-050", topicId: "future", text: "What’s one sentence you’d tell yourself a year from now?" },
  { id: "future-051", topicId: "future", text: "Talk about college applications and what it brings up for you." },
  { id: "future-052", topicId: "future", text: "Describe a recent experience related to gap years." },
  { id: "future-053", topicId: "future", text: "What have you noticed about yourself around first jobs?" },
  { id: "future-054", topicId: "future", text: "How does internships show up in your life right now?" },
  { id: "future-055", topicId: "future", text: "Share a story connected to moving out." },
  { id: "future-056", topicId: "future", text: "Talk about staying local and what it brings up for you." },
  { id: "future-057", topicId: "future", text: "Describe a recent experience related to traveling." },
  { id: "future-058", topicId: "future", text: "What have you noticed about yourself around saving money?" },
  { id: "future-059", topicId: "future", text: "How does career ideas show up in your life right now?" },
  { id: "future-060", topicId: "future", text: "Share a story connected to passion careers." },
  { id: "future-061", topicId: "future", text: "Talk about practical careers and what it brings up for you." },
  { id: "future-062", topicId: "future", text: "Describe a recent experience related to portfolio building." },
  { id: "future-063", topicId: "future", text: "What have you noticed about yourself around networking?" },
  { id: "future-064", topicId: "future", text: "How does mentors show up in your life right now?" },
  { id: "future-065", topicId: "future", text: "Share a story connected to self-teaching." },
  { id: "future-066", topicId: "future", text: "Talk about formal education and what it brings up for you." },
  { id: "future-067", topicId: "future", text: "Describe a recent experience related to creative futures." },
  { id: "future-068", topicId: "future", text: "What have you noticed about yourself around stable futures?" },
  { id: "future-069", topicId: "future", text: "How does hybrid paths show up in your life right now?" },
  { id: "future-070", topicId: "future", text: "Share a story connected to pivots." },
  { id: "future-071", topicId: "future", text: "Talk about timelines and what it brings up for you." },
  { id: "future-072", topicId: "future", text: "Describe a recent experience related to deadlines." },
  { id: "future-073", topicId: "future", text: "What have you noticed about yourself around open calendars?" },
  { id: "future-074", topicId: "future", text: "How does waiting seasons show up in your life right now?" },
  { id: "future-075", topicId: "future", text: "Share a story connected to imposter fears." },
  { id: "future-076", topicId: "future", text: "Talk about confidence spikes and what it brings up for you." },
  { id: "future-077", topicId: "future", text: "Describe a recent experience related to family pressure." },
  { id: "future-078", topicId: "future", text: "What have you noticed about yourself around peer pressure?" },
  { id: "future-079", topicId: "future", text: "How does social media futures show up in your life right now?" },
  { id: "future-080", topicId: "future", text: "Share a story connected to offline dreams." },
  { id: "future-081", topicId: "future", text: "Talk about public goals and what it brings up for you." },
  { id: "future-082", topicId: "future", text: "Describe a recent experience related to private goals." },
  { id: "future-083", topicId: "future", text: "What have you noticed about yourself around relationship futures?" },
  { id: "future-084", topicId: "future", text: "How does solo seasons show up in your life right now?" },
  { id: "future-085", topicId: "future", text: "Share a story connected to community." },
  { id: "future-086", topicId: "future", text: "Talk about chosen family and what it brings up for you." },
  { id: "future-087", topicId: "future", text: "Describe a recent experience related to health goals." },
  { id: "future-088", topicId: "future", text: "What have you noticed about yourself around mental health?" },
  { id: "future-089", topicId: "future", text: "How does financial literacy show up in your life right now?" },
  { id: "future-090", topicId: "future", text: "Share a story connected to independence skills." },
  { id: "future-091", topicId: "future", text: "Talk about voting and citizenship and what it brings up for you." },
  { id: "future-092", topicId: "future", text: "Describe a recent experience related to activism." },
  { id: "future-093", topicId: "future", text: "What have you noticed about yourself around quiet contribution?" },
  { id: "future-094", topicId: "future", text: "How does leadership show up in your life right now?" },
  { id: "future-095", topicId: "future", text: "Share a story connected to art you want to make." },
  { id: "future-096", topicId: "future", text: "Talk about problems you want to solve and what it brings up for you." },
  { id: "future-097", topicId: "future", text: "Describe a recent experience related to places to see." },
  { id: "future-098", topicId: "future", text: "What have you noticed about yourself around people to meet?" },
  { id: "future-099", topicId: "future", text: "How does habits show up in your life right now?" },
  { id: "future-100", topicId: "future", text: "Share a story connected to mindset." },
  { id: "future-101", topicId: "future", text: "Talk about resilience and what it brings up for you." },
  { id: "future-102", topicId: "future", text: "Describe a recent experience related to curiosity." },
  { id: "future-103", topicId: "future", text: "What have you noticed about yourself around saying yes?" },
  { id: "future-104", topicId: "future", text: "How does saying no show up in your life right now?" },
  { id: "future-105", topicId: "future", text: "Share a story connected to starting." },
  { id: "future-106", topicId: "future", text: "Talk about finishing and what it brings up for you." },
];
