import type { BankQuestion } from "@/lib/questions/types";

export const HOBBIES_QUESTIONS: BankQuestion[] = [
  { id: "hobbies-001", topicId: "hobbies", text: "What hobby makes you lose track of time—and why?" },
  { id: "hobbies-002", topicId: "hobbies", text: "Talk about how you first got into something you love." },
  { id: "hobbies-003", topicId: "hobbies", text: "Describe the feeling of being in the middle of your hobby." },
  { id: "hobbies-004", topicId: "hobbies", text: "When do you share your hobby, and when do you keep it private?" },
  { id: "hobbies-005", topicId: "hobbies", text: "What’s hard about sticking with a hobby?" },
  { id: "hobbies-006", topicId: "hobbies", text: "Talk about improving at something just for yourself." },
  { id: "hobbies-007", topicId: "hobbies", text: "Describe a project or piece you’re proud of." },
  { id: "hobbies-008", topicId: "hobbies", text: "How does your hobby change your mood?" },
  { id: "hobbies-009", topicId: "hobbies", text: "What’s expensive, time-consuming, or inconvenient—and still worth it?" },
  { id: "hobbies-010", topicId: "hobbies", text: "Talk about learning from tutorials, friends, or trial and error." },
  { id: "hobbies-011", topicId: "hobbies", text: "Describe teaching your hobby to someone else." },
  { id: "hobbies-012", topicId: "hobbies", text: "When does comparison spoil the fun?" },
  { id: "hobbies-013", topicId: "hobbies", text: "What’s a hobby you quit and might return to?" },
  { id: "hobbies-014", topicId: "hobbies", text: "Talk about collecting, building, making, or playing." },
  { id: "hobbies-015", topicId: "hobbies", text: "Describe your ideal afternoon with your hobby." },
  { id: "hobbies-016", topicId: "hobbies", text: "How do hobbies fit around school, work, or family?" },
  { id: "hobbies-017", topicId: "hobbies", text: "What’s something niche you love that others don’t get?" },
  { id: "hobbies-018", topicId: "hobbies", text: "Talk about community around your hobby—online or in person." },
  { id: "hobbies-019", topicId: "hobbies", text: "Describe a fail that became funny later." },
  { id: "hobbies-020", topicId: "hobbies", text: "When does your hobby feel like rest versus work?" },
  { id: "hobbies-021", topicId: "hobbies", text: "What’s next that you want to try?" },
  { id: "hobbies-022", topicId: "hobbies", text: "Talk about gear, tools, or materials that matter to you." },
  { id: "hobbies-023", topicId: "hobbies", text: "Describe inspiration that kicked off a new idea." },
  { id: "hobbies-024", topicId: "hobbies", text: "How do you handle creative blocks or boredom?" },
  { id: "hobbies-025", topicId: "hobbies", text: "What’s a small daily practice related to your hobby?" },
  { id: "hobbies-026", topicId: "hobbies", text: "Talk about performing or showing your work." },
  { id: "hobbies-027", topicId: "hobbies", text: "Describe solitude while doing something you love." },
  { id: "hobbies-028", topicId: "hobbies", text: "When have you been surprised by your own progress?" },
  { id: "hobbies-029", topicId: "hobbies", text: "What’s the story behind a favorite creation or session?" },
  { id: "hobbies-030", topicId: "hobbies", text: "Talk about hobbies that connect you to people." },
  { id: "hobbies-031", topicId: "hobbies", text: "Describe a hobby that helps you process emotions." },
  { id: "hobbies-032", topicId: "hobbies", text: "How do you choose what to start when you have free time?" },
  { id: "hobbies-033", topicId: "hobbies", text: "What’s something you’ve gotten better at patiently?" },
  { id: "hobbies-034", topicId: "hobbies", text: "Talk about remixing, customizing, or putting your spin on things." },
  { id: "hobbies-035", topicId: "hobbies", text: "Describe jealousy of someone further along—and what you did with it." },
  { id: "hobbies-036", topicId: "hobbies", text: "When does playfulness lead the way?" },
  { id: "hobbies-037", topicId: "hobbies", text: "What’s a rule you made for yourself in your hobby?" },
  { id: "hobbies-038", topicId: "hobbies", text: "Talk about seasons—times you dive in and times you pause." },
  { id: "hobbies-039", topicId: "hobbies", text: "Describe recommending your hobby to a friend." },
  { id: "hobbies-040", topicId: "hobbies", text: "How has your taste changed over time?" },
  { id: "hobbies-041", topicId: "hobbies", text: "What’s messy, imperfect, and still satisfying?" },
  { id: "hobbies-042", topicId: "hobbies", text: "Talk about documenting your hobby—photos, journals, posts." },
  { id: "hobbies-043", topicId: "hobbies", text: "Describe a collaborative hobby experience." },
  { id: "hobbies-044", topicId: "hobbies", text: "When do you feel most skilled?" },
  { id: "hobbies-045", topicId: "hobbies", text: "What’s beginner energy you want to keep?" },
  { id: "hobbies-046", topicId: "hobbies", text: "Talk about a hobby that scared you at first." },
  { id: "hobbies-047", topicId: "hobbies", text: "Describe the soundtrack or atmosphere of your hobby time." },
  { id: "hobbies-048", topicId: "hobbies", text: "How do you protect time for what you love?" },
  { id: "hobbies-049", topicId: "hobbies", text: "What’s joyful about being a beginner again?" },
  { id: "hobbies-050", topicId: "hobbies", text: "Talk about how this hobby shows up in who you’re becoming." },
  { id: "hobbies-051", topicId: "hobbies", text: "Talk about drawing and what it brings up for you." },
  { id: "hobbies-052", topicId: "hobbies", text: "Describe a recent experience related to writing." },
  { id: "hobbies-053", topicId: "hobbies", text: "What have you noticed about yourself around coding side projects?" },
  { id: "hobbies-054", topicId: "hobbies", text: "How does gaming show up in your life right now?" },
  { id: "hobbies-055", topicId: "hobbies", text: "Share a story connected to music practice." },
  { id: "hobbies-056", topicId: "hobbies", text: "Talk about cooking and what it brings up for you." },
  { id: "hobbies-057", topicId: "hobbies", text: "Describe a recent experience related to baking." },
  { id: "hobbies-058", topicId: "hobbies", text: "What have you noticed about yourself around gardening?" },
  { id: "hobbies-059", topicId: "hobbies", text: "How does photography show up in your life right now?" },
  { id: "hobbies-060", topicId: "hobbies", text: "Share a story connected to editing videos." },
  { id: "hobbies-061", topicId: "hobbies", text: "Talk about knitting and what it brings up for you." },
  { id: "hobbies-062", topicId: "hobbies", text: "Describe a recent experience related to building models." },
  { id: "hobbies-063", topicId: "hobbies", text: "What have you noticed about yourself around skateboarding?" },
  { id: "hobbies-064", topicId: "hobbies", text: "How does dancing show up in your life right now?" },
  { id: "hobbies-065", topicId: "hobbies", text: "Share a story connected to singing." },
  { id: "hobbies-066", topicId: "hobbies", text: "Talk about journaling and what it brings up for you." },
  { id: "hobbies-067", topicId: "hobbies", text: "Describe a recent experience related to reading." },
  { id: "hobbies-068", topicId: "hobbies", text: "What have you noticed about yourself around puzzles?" },
  { id: "hobbies-069", topicId: "hobbies", text: "How does board games show up in your life right now?" },
  { id: "hobbies-070", topicId: "hobbies", text: "Share a story connected to card games." },
  { id: "hobbies-071", topicId: "hobbies", text: "Talk about hiking and what it brings up for you." },
  { id: "hobbies-072", topicId: "hobbies", text: "Describe a recent experience related to running for fun." },
  { id: "hobbies-073", topicId: "hobbies", text: "What have you noticed about yourself around yoga?" },
  { id: "hobbies-074", topicId: "hobbies", text: "How does stretching show up in your life right now?" },
  { id: "hobbies-075", topicId: "hobbies", text: "Share a story connected to collecting." },
  { id: "hobbies-076", topicId: "hobbies", text: "Talk about thrifting and what it brings up for you." },
  { id: "hobbies-077", topicId: "hobbies", text: "Describe a recent experience related to DIY fixes." },
  { id: "hobbies-078", topicId: "hobbies", text: "What have you noticed about yourself around decorating?" },
  { id: "hobbies-079", topicId: "hobbies", text: "How does podcasts show up in your life right now?" },
  { id: "hobbies-080", topicId: "hobbies", text: "Share a story connected to learning languages." },
  { id: "hobbies-081", topicId: "hobbies", text: "Talk about magic tricks and what it brings up for you." },
  { id: "hobbies-082", topicId: "hobbies", text: "Describe a recent experience related to comedy." },
  { id: "hobbies-083", topicId: "hobbies", text: "What have you noticed about yourself around astronomy?" },
  { id: "hobbies-084", topicId: "hobbies", text: "How does birdwatching show up in your life right now?" },
  { id: "hobbies-085", topicId: "hobbies", text: "Share a story connected to fishing." },
  { id: "hobbies-086", topicId: "hobbies", text: "Talk about camping skills and what it brings up for you." },
  { id: "hobbies-087", topicId: "hobbies", text: "Describe a recent experience related to calligraphy." },
  { id: "hobbies-088", topicId: "hobbies", text: "What have you noticed about yourself around pottery?" },
  { id: "hobbies-089", topicId: "hobbies", text: "How does sculpture show up in your life right now?" },
  { id: "hobbies-090", topicId: "hobbies", text: "Share a story connected to animation." },
  { id: "hobbies-091", topicId: "hobbies", text: "Talk about beatmaking and what it brings up for you." },
  { id: "hobbies-092", topicId: "hobbies", text: "Describe a recent experience related to playlists." },
  { id: "hobbies-093", topicId: "hobbies", text: "What have you noticed about yourself around fan communities?" },
  { id: "hobbies-094", topicId: "hobbies", text: "How does conventions show up in your life right now?" },
  { id: "hobbies-095", topicId: "hobbies", text: "Share a story connected to weekend projects." },
  { id: "hobbies-096", topicId: "hobbies", text: "Talk about tiny daily habits and what it brings up for you." },
  { id: "hobbies-097", topicId: "hobbies", text: "Describe a recent experience related to messy desks." },
  { id: "hobbies-098", topicId: "hobbies", text: "What have you noticed about yourself around clean setups?" },
  { id: "hobbies-099", topicId: "hobbies", text: "How does sharing online show up in your life right now?" },
  { id: "hobbies-100", topicId: "hobbies", text: "Share a story connected to keeping offline." },
  { id: "hobbies-101", topicId: "hobbies", text: "Talk about gifting what you make and what it brings up for you." },
  { id: "hobbies-102", topicId: "hobbies", text: "Describe a recent experience related to keeping it." },
];
