import type { BankQuestion } from "@/lib/questions/types";

export const RELATIONSHIPS_QUESTIONS: BankQuestion[] = [
  { id: "relationships-001", topicId: "relationships", text: "What does closeness mean to you right now?" },
  { id: "relationships-002", topicId: "relationships", text: "Talk about a relationship that taught you something important." },
  { id: "relationships-003", topicId: "relationships", text: "How do you show affection in ways that feel natural?" },
  { id: "relationships-004", topicId: "relationships", text: "Describe a conversation that brought you closer to someone." },
  { id: "relationships-005", topicId: "relationships", text: "When is communication hardest for you?" },
  { id: "relationships-006", topicId: "relationships", text: "What boundaries help you feel respected?" },
  { id: "relationships-007", topicId: "relationships", text: "Talk about trust—how do you build it?" },
  { id: "relationships-008", topicId: "relationships", text: "Describe a time you felt truly seen by someone." },
  { id: "relationships-009", topicId: "relationships", text: "What makes you pull back in a close relationship?" },
  { id: "relationships-010", topicId: "relationships", text: "How do you handle conflict without shutting down?" },
  { id: "relationships-011", topicId: "relationships", text: "Talk about saying something vulnerable out loud." },
  { id: "relationships-012", topicId: "relationships", text: "What does a healthy relationship look like to you?" },
  { id: "relationships-013", topicId: "relationships", text: "Describe supporting someone you care about." },
  { id: "relationships-014", topicId: "relationships", text: "When do you need reassurance?" },
  { id: "relationships-015", topicId: "relationships", text: "What’s hard about asking for what you need?" },
  { id: "relationships-016", topicId: "relationships", text: "Talk about jealousy or insecurity you’ve felt." },
  { id: "relationships-017", topicId: "relationships", text: "Describe a small gesture that meant a lot." },
  { id: "relationships-018", topicId: "relationships", text: "How do you rebuild after a misunderstanding?" },
  { id: "relationships-019", topicId: "relationships", text: "What qualities do you value most in a partner or close person?" },
  { id: "relationships-020", topicId: "relationships", text: "Talk about independence inside closeness." },
  { id: "relationships-021", topicId: "relationships", text: "When do you feel most connected?" },
  { id: "relationships-022", topicId: "relationships", text: "Describe a hard truth you shared carefully." },
  { id: "relationships-023", topicId: "relationships", text: "How do phones and texting affect your closeness?" },
  { id: "relationships-024", topicId: "relationships", text: "What’s changing in how you approach relationships?" },
  { id: "relationships-025", topicId: "relationships", text: "Talk about a breakup or distance that shaped you." },
  { id: "relationships-026", topicId: "relationships", text: "Describe feeling safe enough to be silly." },
  { id: "relationships-027", topicId: "relationships", text: "What does loyalty look like day to day?" },
  { id: "relationships-028", topicId: "relationships", text: "How do you celebrate someone you care about?" },
  { id: "relationships-029", topicId: "relationships", text: "Talk about timing—when someone was ready and you weren’t, or vice versa." },
  { id: "relationships-030", topicId: "relationships", text: "What makes you feel chosen?" },
  { id: "relationships-031", topicId: "relationships", text: "Describe listening well when it mattered." },
  { id: "relationships-032", topicId: "relationships", text: "How do you know you’re growing in how you love?" },
  { id: "relationships-033", topicId: "relationships", text: "Talk about compromise that still felt fair." },
  { id: "relationships-034", topicId: "relationships", text: "When do expectations get heavy?" },
  { id: "relationships-035", topicId: "relationships", text: "What’s something you’re learning not to take personally?" },
  { id: "relationships-036", topicId: "relationships", text: "Describe a quiet comfortable silence with someone." },
  { id: "relationships-037", topicId: "relationships", text: "How do you talk about the future with someone close?" },
  { id: "relationships-038", topicId: "relationships", text: "What scares you about getting closer?" },
  { id: "relationships-039", topicId: "relationships", text: "Talk about apologizing when you were wrong." },
  { id: "relationships-040", topicId: "relationships", text: "Describe receiving an apology that mattered." },
  { id: "relationships-041", topicId: "relationships", text: "How do friendships and romantic feelings differ for you?" },
  { id: "relationships-042", topicId: "relationships", text: "What’s a green flag you notice now that you didn’t before?" },
  { id: "relationships-043", topicId: "relationships", text: "Talk about space—needing it and giving it." },
  { id: "relationships-044", topicId: "relationships", text: "When do you feel most like yourself with someone?" },
  { id: "relationships-045", topicId: "relationships", text: "Describe a shared routine that feels intimate." },
  { id: "relationships-046", topicId: "relationships", text: "How do you handle different communication styles?" },
  { id: "relationships-047", topicId: "relationships", text: "What’s something you want to practice saying more clearly?" },
  { id: "relationships-048", topicId: "relationships", text: "Talk about attraction versus connection." },
  { id: "relationships-049", topicId: "relationships", text: "Describe protecting your heart without closing it." },
  { id: "relationships-050", topicId: "relationships", text: "What does respect sound like in an argument?" },
  { id: "relationships-051", topicId: "relationships", text: "Talk about first dates energy and what it brings up for you." },
  { id: "relationships-052", topicId: "relationships", text: "Describe a recent experience related to long talks." },
  { id: "relationships-053", topicId: "relationships", text: "What have you noticed about yourself around short check-ins?" },
  { id: "relationships-054", topicId: "relationships", text: "How does mixed signals show up in your life right now?" },
  { id: "relationships-055", topicId: "relationships", text: "Share a story connected to clear signals." },
  { id: "relationships-056", topicId: "relationships", text: "Talk about butterflies and what it brings up for you." },
  { id: "relationships-057", topicId: "relationships", text: "Describe a recent experience related to calm certainty." },
  { id: "relationships-058", topicId: "relationships", text: "What have you noticed about yourself around growing slowly?" },
  { id: "relationships-059", topicId: "relationships", text: "How does moving too fast show up in your life right now?" },
  { id: "relationships-060", topicId: "relationships", text: "Share a story connected to saying I miss you." },
  { id: "relationships-061", topicId: "relationships", text: "Talk about saying I need space and what it brings up for you." },
  { id: "relationships-062", topicId: "relationships", text: "Describe a recent experience related to holding hands vibes." },
  { id: "relationships-063", topicId: "relationships", text: "What have you noticed about yourself around inside jokes?" },
  { id: "relationships-064", topicId: "relationships", text: "How does shared goals show up in your life right now?" },
  { id: "relationships-065", topicId: "relationships", text: "Share a story connected to different goals." },
  { id: "relationships-066", topicId: "relationships", text: "Talk about meeting their people and what it brings up for you." },
  { id: "relationships-067", topicId: "relationships", text: "Describe a recent experience related to introducing them." },
  { id: "relationships-068", topicId: "relationships", text: "What have you noticed about yourself around public vs private?" },
  { id: "relationships-069", topicId: "relationships", text: "How does social media show up in your life right now?" },
  { id: "relationships-070", topicId: "relationships", text: "Share a story connected to privacy." },
  { id: "relationships-071", topicId: "relationships", text: "Talk about flirting and what it brings up for you." },
  { id: "relationships-072", topicId: "relationships", text: "Describe a recent experience related to friendship first." },
  { id: "relationships-073", topicId: "relationships", text: "What have you noticed about yourself around rekindling?" },
  { id: "relationships-074", topicId: "relationships", text: "How does letting go show up in your life right now?" },
  { id: "relationships-075", topicId: "relationships", text: "Share a story connected to crush confusion." },
  { id: "relationships-076", topicId: "relationships", text: "Talk about mutual care and what it brings up for you." },
  { id: "relationships-077", topicId: "relationships", text: "Describe a recent experience related to uneven effort." },
  { id: "relationships-078", topicId: "relationships", text: "What have you noticed about yourself around matching effort?" },
  { id: "relationships-079", topicId: "relationships", text: "How does hard conversations show up in your life right now?" },
  { id: "relationships-080", topicId: "relationships", text: "Share a story connected to easy laughter." },
  { id: "relationships-081", topicId: "relationships", text: "Talk about teasing kindly and what it brings up for you." },
  { id: "relationships-082", topicId: "relationships", text: "Describe a recent experience related to teasing that hurts." },
  { id: "relationships-083", topicId: "relationships", text: "What have you noticed about yourself around gifts?" },
  { id: "relationships-084", topicId: "relationships", text: "How does time show up in your life right now?" },
  { id: "relationships-085", topicId: "relationships", text: "Share a story connected to words." },
  { id: "relationships-086", topicId: "relationships", text: "Talk about acts of service and what it brings up for you." },
  { id: "relationships-087", topicId: "relationships", text: "Describe a recent experience related to feeling secure." },
  { id: "relationships-088", topicId: "relationships", text: "What have you noticed about yourself around feeling unsure?" },
  { id: "relationships-089", topicId: "relationships", text: "How does past patterns show up in your life right now?" },
  { id: "relationships-090", topicId: "relationships", text: "Share a story connected to new patterns." },
  { id: "relationships-091", topicId: "relationships", text: "Talk about honesty and what it brings up for you." },
  { id: "relationships-092", topicId: "relationships", text: "Describe a recent experience related to gentleness." },
  { id: "relationships-093", topicId: "relationships", text: "What have you noticed about yourself around passion?" },
  { id: "relationships-094", topicId: "relationships", text: "How does patience show up in your life right now?" },
  { id: "relationships-095", topicId: "relationships", text: "Share a story connected to commitment talk." },
  { id: "relationships-096", topicId: "relationships", text: "Talk about casual talk and what it brings up for you." },
  { id: "relationships-097", topicId: "relationships", text: "Describe a recent experience related to future talk." },
  { id: "relationships-098", topicId: "relationships", text: "What have you noticed about yourself around present moment?" },
  { id: "relationships-099", topicId: "relationships", text: "How does repair after conflict show up in your life right now?" },
  { id: "relationships-100", topicId: "relationships", text: "Share a story connected to avoiding conflict." },
  { id: "relationships-101", topicId: "relationships", text: "Talk about naming feelings and what it brings up for you." },
  { id: "relationships-102", topicId: "relationships", text: "Describe a recent experience related to naming needs." },
];
