import type { BankQuestion } from "@/lib/questions/types";

export const SCHOOL_QUESTIONS: BankQuestion[] = [
  { id: "school-001", topicId: "school", text: "What’s something you learned this week that stuck with you?" },
  { id: "school-002", topicId: "school", text: "Talk about a class where you feel most yourself." },
  { id: "school-003", topicId: "school", text: "When does school pressure show up in your body or voice?" },
  { id: "school-004", topicId: "school", text: "Describe a teacher or mentor who influenced you." },
  { id: "school-005", topicId: "school", text: "How do you handle a grade that disappointed you?" },
  { id: "school-006", topicId: "school", text: "Talk about working in a group at school." },
  { id: "school-007", topicId: "school", text: "What subject challenges you—and how do you face it?" },
  { id: "school-008", topicId: "school", text: "Describe a moment you felt proud at school." },
  { id: "school-009", topicId: "school", text: "When do you compare yourself to classmates?" },
  { id: "school-010", topicId: "school", text: "What’s your relationship with asking questions in class?" },
  { id: "school-011", topicId: "school", text: "Talk about a project you cared about." },
  { id: "school-012", topicId: "school", text: "How do mornings before school usually feel?" },
  { id: "school-013", topicId: "school", text: "Describe a friendship that exists mostly at school." },
  { id: "school-014", topicId: "school", text: "What does belonging feel like in your school?" },
  { id: "school-015", topicId: "school", text: "Talk about speaking up when something felt unfair." },
  { id: "school-016", topicId: "school", text: "How do you study when motivation is low?" },
  { id: "school-017", topicId: "school", text: "Describe feedback that helped you grow." },
  { id: "school-018", topicId: "school", text: "When do you feel invisible at school?" },
  { id: "school-019", topicId: "school", text: "What’s something school brings out in you?" },
  { id: "school-020", topicId: "school", text: "Talk about balancing school with the rest of life." },
  { id: "school-021", topicId: "school", text: "Describe a presentation or performance you gave." },
  { id: "school-022", topicId: "school", text: "How do tests affect how you talk about yourself?" },
  { id: "school-023", topicId: "school", text: "What’s a goal you’re working toward at school?" },
  { id: "school-024", topicId: "school", text: "Talk about a setback and what you did next." },
  { id: "school-025", topicId: "school", text: "When is curiosity strongest for you at school?" },
  { id: "school-026", topicId: "school", text: "Describe lunch, free periods, or in-between moments." },
  { id: "school-027", topicId: "school", text: "How do you handle competition with peers?" },
  { id: "school-028", topicId: "school", text: "What’s changing about how you see school?" },
  { id: "school-029", topicId: "school", text: "Talk about asking for help from a teacher." },
  { id: "school-030", topicId: "school", text: "Describe a club, team, or activity tied to school." },
  { id: "school-031", topicId: "school", text: "When do you feel confident raising your hand?" },
  { id: "school-032", topicId: "school", text: "What’s hard about group chats and school drama?" },
  { id: "school-033", topicId: "school", text: "Talk about time management—what’s working or not?" },
  { id: "school-034", topicId: "school", text: "Describe learning something outside the curriculum that still helped at school." },
  { id: "school-035", topicId: "school", text: "How do you talk about your future plans at school?" },
  { id: "school-036", topicId: "school", text: "What’s a rumor or social pressure you’ve noticed?" },
  { id: "school-037", topicId: "school", text: "Talk about a day that felt especially long." },
  { id: "school-038", topicId: "school", text: "Describe collaborating with someone unexpected." },
  { id: "school-039", topicId: "school", text: "When do you feel creative at school?" },
  { id: "school-040", topicId: "school", text: "What’s your honest relationship with homework?" },
  { id: "school-041", topicId: "school", text: "Talk about identity—who you are at school vs elsewhere." },
  { id: "school-042", topicId: "school", text: "Describe a moment of kindness in a hallway or classroom." },
  { id: "school-043", topicId: "school", text: "How do you recover after a bad day at school?" },
  { id: "school-044", topicId: "school", text: "What’s something you wish adults understood about school now?" },
  { id: "school-045", topicId: "school", text: "Talk about leadership you took on, even small." },
  { id: "school-046", topicId: "school", text: "Describe preparing for something important." },
  { id: "school-047", topicId: "school", text: "When does school feel meaningful?" },
  { id: "school-048", topicId: "school", text: "What’s a skill school is quietly teaching you?" },
  { id: "school-049", topicId: "school", text: "Talk about inclusion—who gets heard and who doesn’t." },
  { id: "school-050", topicId: "school", text: "How do you want to grow as a student this year?" },
  { id: "school-051", topicId: "school", text: "Talk about math class and what it brings up for you." },
  { id: "school-052", topicId: "school", text: "Describe a recent experience related to writing." },
  { id: "school-053", topicId: "school", text: "What have you noticed about yourself around science labs?" },
  { id: "school-054", topicId: "school", text: "How does art show up in your life right now?" },
  { id: "school-055", topicId: "school", text: "Share a story connected to music." },
  { id: "school-056", topicId: "school", text: "Talk about PE and what it brings up for you." },
  { id: "school-057", topicId: "school", text: "Describe a recent experience related to study halls." },
  { id: "school-058", topicId: "school", text: "What have you noticed about yourself around libraries?" },
  { id: "school-059", topicId: "school", text: "How does lockers show up in your life right now?" },
  { id: "school-060", topicId: "school", text: "Share a story connected to buses." },
  { id: "school-061", topicId: "school", text: "Talk about walking to class and what it brings up for you." },
  { id: "school-062", topicId: "school", text: "Describe a recent experience related to deadlines." },
  { id: "school-063", topicId: "school", text: "What have you noticed about yourself around extensions?" },
  { id: "school-064", topicId: "school", text: "How does all-nighters show up in your life right now?" },
  { id: "school-065", topicId: "school", text: "Share a story connected to early nights." },
  { id: "school-066", topicId: "school", text: "Talk about caffeine and what it brings up for you." },
  { id: "school-067", topicId: "school", text: "Describe a recent experience related to group chats." },
  { id: "school-068", topicId: "school", text: "What have you noticed about yourself around group projects?" },
  { id: "school-069", topicId: "school", text: "How does solo work show up in your life right now?" },
  { id: "school-070", topicId: "school", text: "Share a story connected to presentations." },
  { id: "school-071", topicId: "school", text: "Talk about pop quizzes and what it brings up for you." },
  { id: "school-072", topicId: "school", text: "Describe a recent experience related to big exams." },
  { id: "school-073", topicId: "school", text: "What have you noticed about yourself around essays?" },
  { id: "school-074", topicId: "school", text: "How does portfolios show up in your life right now?" },
  { id: "school-075", topicId: "school", text: "Share a story connected to sports after school." },
  { id: "school-076", topicId: "school", text: "Talk about jobs after school and what it brings up for you." },
  { id: "school-077", topicId: "school", text: "Describe a recent experience related to tutoring." },
  { id: "school-078", topicId: "school", text: "What have you noticed about yourself around office hours?" },
  { id: "school-079", topicId: "school", text: "How does new classes show up in your life right now?" },
  { id: "school-080", topicId: "school", text: "Share a story connected to old routines." },
  { id: "school-081", topicId: "school", text: "Talk about senior vibes and what it brings up for you." },
  { id: "school-082", topicId: "school", text: "Describe a recent experience related to starting fresh." },
  { id: "school-083", topicId: "school", text: "What have you noticed about yourself around feeling behind?" },
  { id: "school-084", topicId: "school", text: "How does feeling ahead show up in your life right now?" },
  { id: "school-085", topicId: "school", text: "Share a story connected to imposter feelings." },
  { id: "school-086", topicId: "school", text: "Talk about confidence spikes and what it brings up for you." },
  { id: "school-087", topicId: "school", text: "Describe a recent experience related to teacher feedback." },
  { id: "school-088", topicId: "school", text: "What have you noticed about yourself around peer feedback?" },
  { id: "school-089", topicId: "school", text: "How does self-critique show up in your life right now?" },
  { id: "school-090", topicId: "school", text: "Share a story connected to self-compassion." },
  { id: "school-091", topicId: "school", text: "Talk about hallway noise and what it brings up for you." },
  { id: "school-092", topicId: "school", text: "Describe a recent experience related to quiet corners." },
  { id: "school-093", topicId: "school", text: "What have you noticed about yourself around assemblies?" },
  { id: "school-094", topicId: "school", text: "How does spirit days show up in your life right now?" },
  { id: "school-095", topicId: "school", text: "Share a story connected to clubs." },
  { id: "school-096", topicId: "school", text: "Talk about student government and what it brings up for you." },
  { id: "school-097", topicId: "school", text: "Describe a recent experience related to volunteer hours." },
  { id: "school-098", topicId: "school", text: "What have you noticed about yourself around internships?" },
  { id: "school-099", topicId: "school", text: "How does college talk show up in your life right now?" },
  { id: "school-100", topicId: "school", text: "Share a story connected to career talk." },
  { id: "school-101", topicId: "school", text: "Talk about gap year thoughts and what it brings up for you." },
  { id: "school-102", topicId: "school", text: "Describe a recent experience related to uncertainty." },
  { id: "school-103", topicId: "school", text: "What have you noticed about yourself around focus days?" },
  { id: "school-104", topicId: "school", text: "How does distracted days show up in your life right now?" },
  { id: "school-105", topicId: "school", text: "Share a story connected to friend drama." },
  { id: "school-106", topicId: "school", text: "Talk about academic wins and what it brings up for you." },
];
