import type { BankQuestion } from "@/lib/questions/types";

export const SPORTS_QUESTIONS: BankQuestion[] = [
  { id: "sports-001", topicId: "sports", text: "What does competing bring out in you?" },
  { id: "sports-002", topicId: "sports", text: "Talk about a game, match, or practice that stayed with you." },
  { id: "sports-003", topicId: "sports", text: "How do you handle winning—and how do you handle losing?" },
  { id: "sports-004", topicId: "sports", text: "Describe your role on a team, even an informal one." },
  { id: "sports-005", topicId: "sports", text: "When does pressure help you, and when does it hurt?" },
  { id: "sports-006", topicId: "sports", text: "Talk about discipline—what routines keep you going?" },
  { id: "sports-007", topicId: "sports", text: "Describe a coach, captain, or teammate who shaped you." },
  { id: "sports-008", topicId: "sports", text: "What does teamwork sound like when it’s working?" },
  { id: "sports-009", topicId: "sports", text: "Talk about an injury, setback, or time on the bench." },
  { id: "sports-010", topicId: "sports", text: "How do sports affect your confidence off the field?" },
  { id: "sports-011", topicId: "sports", text: "Describe warming up—mentally and physically." },
  { id: "sports-012", topicId: "sports", text: "When do you feel most in flow while playing?" },
  { id: "sports-013", topicId: "sports", text: "What’s hard about balancing sports with everything else?" },
  { id: "sports-014", topicId: "sports", text: "Talk about sportsmanship that mattered." },
  { id: "sports-015", topicId: "sports", text: "Describe a rivalry that pushed you to grow." },
  { id: "sports-016", topicId: "sports", text: "How do you talk to yourself after a mistake in a game?" },
  { id: "sports-017", topicId: "sports", text: "What’s a skill you’ve been grinding to improve?" },
  { id: "sports-018", topicId: "sports", text: "Talk about belonging on a team—or not belonging." },
  { id: "sports-019", topicId: "sports", text: "Describe celebrating a teammate’s success." },
  { id: "sports-020", topicId: "sports", text: "When do you prefer individual sports or team sports?" },
  { id: "sports-021", topicId: "sports", text: "What’s changing about your relationship with sports?" },
  { id: "sports-022", topicId: "sports", text: "Talk about nerves before a big moment." },
  { id: "sports-023", topicId: "sports", text: "Describe teaching someone a skill from your sport." },
  { id: "sports-024", topicId: "sports", text: "How do fans, parents, or spectators affect you?" },
  { id: "sports-025", topicId: "sports", text: "What’s fair and unfair about how people judge athletes?" },
  { id: "sports-026", topicId: "sports", text: "Talk about quitting something—or almost quitting." },
  { id: "sports-027", topicId: "sports", text: "Describe a practice that felt pointless—and what you learned anyway." },
  { id: "sports-028", topicId: "sports", text: "When does playfulness show up in competition?" },
  { id: "sports-029", topicId: "sports", text: "What’s your pre-game or pre-practice ritual?" },
  { id: "sports-030", topicId: "sports", text: "Talk about leadership you showed without a title." },
  { id: "sports-031", topicId: "sports", text: "Describe recovering after a tough loss." },
  { id: "sports-032", topicId: "sports", text: "How do you stay motivated in the off-season?" },
  { id: "sports-033", topicId: "sports", text: "What’s something sports taught you about your body?" },
  { id: "sports-034", topicId: "sports", text: "Talk about comparing yourself to better players." },
  { id: "sports-035", topicId: "sports", text: "Describe a moment you surprised yourself." },
  { id: "sports-036", topicId: "sports", text: "When is rest part of training for you?" },
  { id: "sports-037", topicId: "sports", text: "What’s the difference between hard work and burnout?" },
  { id: "sports-038", topicId: "sports", text: "Talk about a rule, call, or referee moment that frustrated you." },
  { id: "sports-039", topicId: "sports", text: "Describe chemistry with a teammate." },
  { id: "sports-040", topicId: "sports", text: "How do you handle being benched or rotated?" },
  { id: "sports-041", topicId: "sports", text: "What’s joyful about your sport when you strip away pressure?" },
  { id: "sports-042", topicId: "sports", text: "Talk about representing something bigger than yourself." },
  { id: "sports-043", topicId: "sports", text: "Describe trying a new sport or position." },
  { id: "sports-044", topicId: "sports", text: "When do you feel pride that isn’t about the scoreboard?" },
  { id: "sports-045", topicId: "sports", text: "What’s a sports memory from earlier in life that still matters?" },
  { id: "sports-046", topicId: "sports", text: "Talk about communication on the field or court." },
  { id: "sports-047", topicId: "sports", text: "Describe supporting a friend through their sport journey." },
  { id: "sports-048", topicId: "sports", text: "How has competition changed how you see failure?" },
  { id: "sports-049", topicId: "sports", text: "What’s next for you in sports—or after sports?" },
  { id: "sports-050", topicId: "sports", text: "Talk about the sounds and feeling of your favorite playing space." },
  { id: "sports-051", topicId: "sports", text: "Talk about practice grind and what it brings up for you." },
  { id: "sports-052", topicId: "sports", text: "Describe a recent experience related to game day." },
  { id: "sports-053", topicId: "sports", text: "What have you noticed about yourself around tryouts?" },
  { id: "sports-054", topicId: "sports", text: "How does making the team show up in your life right now?" },
  { id: "sports-055", topicId: "sports", text: "Share a story connected to not making the team." },
  { id: "sports-056", topicId: "sports", text: "Talk about captaincy and what it brings up for you." },
  { id: "sports-057", topicId: "sports", text: "Describe a recent experience related to bench roles." },
  { id: "sports-058", topicId: "sports", text: "What have you noticed about yourself around starting roles?" },
  { id: "sports-059", topicId: "sports", text: "How does conditioning show up in your life right now?" },
  { id: "sports-060", topicId: "sports", text: "Share a story connected to drills." },
  { id: "sports-061", topicId: "sports", text: "Talk about scrimmages and what it brings up for you." },
  { id: "sports-062", topicId: "sports", text: "Describe a recent experience related to film study." },
  { id: "sports-063", topicId: "sports", text: "What have you noticed about yourself around home games?" },
  { id: "sports-064", topicId: "sports", text: "How does away games show up in your life right now?" },
  { id: "sports-065", topicId: "sports", text: "Share a story connected to travel." },
  { id: "sports-066", topicId: "sports", text: "Talk about early mornings and what it brings up for you." },
  { id: "sports-067", topicId: "sports", text: "Describe a recent experience related to late practices." },
  { id: "sports-068", topicId: "sports", text: "What have you noticed about yourself around weekend tournaments?" },
  { id: "sports-069", topicId: "sports", text: "How does championship energy show up in your life right now?" },
  { id: "sports-070", topicId: "sports", text: "Share a story connected to regular season." },
  { id: "sports-071", topicId: "sports", text: "Talk about personal bests and what it brings up for you." },
  { id: "sports-072", topicId: "sports", text: "Describe a recent experience related to team goals." },
  { id: "sports-073", topicId: "sports", text: "What have you noticed about yourself around stats?" },
  { id: "sports-074", topicId: "sports", text: "How does effort over stats show up in your life right now?" },
  { id: "sports-075", topicId: "sports", text: "Share a story connected to coaching styles." },
  { id: "sports-076", topicId: "sports", text: "Talk about tough love and what it brings up for you." },
  { id: "sports-077", topicId: "sports", text: "Describe a recent experience related to encouragement." },
  { id: "sports-078", topicId: "sports", text: "What have you noticed about yourself around silence from coaches?" },
  { id: "sports-079", topicId: "sports", text: "How does parents on the sidelines show up in your life right now?" },
  { id: "sports-080", topicId: "sports", text: "Share a story connected to friends watching." },
  { id: "sports-081", topicId: "sports", text: "Talk about nobody watching and what it brings up for you." },
  { id: "sports-082", topicId: "sports", text: "Describe a recent experience related to highlights." },
  { id: "sports-083", topicId: "sports", text: "What have you noticed about yourself around mistakes on replay?" },
  { id: "sports-084", topicId: "sports", text: "How does clutch moments show up in your life right now?" },
  { id: "sports-085", topicId: "sports", text: "Share a story connected to choking moments." },
  { id: "sports-086", topicId: "sports", text: "Talk about comebacks and what it brings up for you." },
  { id: "sports-087", topicId: "sports", text: "Describe a recent experience related to stretching." },
  { id: "sports-088", topicId: "sports", text: "What have you noticed about yourself around hydration?" },
  { id: "sports-089", topicId: "sports", text: "How does sleep show up in your life right now?" },
  { id: "sports-090", topicId: "sports", text: "Share a story connected to nutrition." },
  { id: "sports-091", topicId: "sports", text: "Talk about team bus and what it brings up for you." },
  { id: "sports-092", topicId: "sports", text: "Describe a recent experience related to locker room." },
  { id: "sports-093", topicId: "sports", text: "What have you noticed about yourself around huddles?" },
  { id: "sports-094", topicId: "sports", text: "How does pep talks show up in your life right now?" },
  { id: "sports-095", topicId: "sports", text: "Share a story connected to trash talk." },
  { id: "sports-096", topicId: "sports", text: "Talk about keeping cool and what it brings up for you." },
  { id: "sports-097", topicId: "sports", text: "Describe a recent experience related to sportsmanship awards." },
  { id: "sports-098", topicId: "sports", text: "What have you noticed about yourself around unsung effort?" },
  { id: "sports-099", topicId: "sports", text: "How does cross-training show up in your life right now?" },
  { id: "sports-100", topicId: "sports", text: "Share a story connected to new gear." },
  { id: "sports-101", topicId: "sports", text: "Talk about old lucky socks and what it brings up for you." },
  { id: "sports-102", topicId: "sports", text: "Describe a recent experience related to weather games." },
];
